---
features:
  - |
    Add two new playbooks to support enabling or disabling of KVM nested virtualisation.
security:
  - |
    Playbook added to support disabling of KVM nested virtualisation in response to
    `CVE-2026-53359 <https://www.openwall.com/lists/oss-security/2026/07/06/7>`__. This
    playbook acts as early mitigation to the vulnerability in lieu of kernel patches.
