---
features:
  - |
    Added a playbook for unsealing secret store deployed at CI runners (Hosts
    in github-runners or gitlab-runners inventory group).
    To run CI after rebooting CI runners, secret store needs to be unsealed
    using this playbook.
