---
upgrade:
  - |
    The playbooks under ``etc/kayobe/ansible`` have been subdivided into
    different categories to make them easier to navigate. This change may
    result in merge conflicts where playbooks have been edited downstream, and
    broken hooks where symlinks have been used.

    To mitigate the impact of these changes, two scripts have been added to
    help fix broken links. ``tools/get-new-playbook-path.sh`` returns the new
    category of a given playbook, and ``tools/magic-symlink-fix.sh`` attempts
    to fix any broken symlinks in the kayobe configuration.
