---
features:
  - |
    Add ``kolla_ceph_conf_append`` configuration option to specify a string
    to be appended to all ceph.conf files gathered from a ceph cluster using
    ``kayobe playbook run $KAYOBE_CONFIG_PATH/ansible/cephadm-gather-keys.yml``.
