---
features:
  - |
    The Ironic Prometheus Exporter is now disabled by default as redfish exporter
    is preferred. If you need to use the Ironic Prometheus Exporter, you can
    enable it by setting the `kolla_enable_ironic_prometheus_exporter`
    option to `true`.
