---
fixes:
  - |
    Bumps Bifrost container image tags to fix `bug 2072550
    <https://bugs.launchpad.net/kayobe/+bug/2072550>`__ which adds
    leading and trailing whitespace for ``inspection_callback_url``
    in httpboot config when templating.
