---
fixes:
  - |
    Changed the Prometheus job name of OS Capacity exporter to
    ``os_capacity`` which is what Azimuth is expecting to have for
    `cloud metrics dashboard <https://github.com/azimuth-cloud/ansible-collection-azimuth-ops/blob/main/roles/cloud_metrics/defaults/main.yml#L41C1-L43C48>`__.
