---
features:
  - |
    ``ironic-prometheus-exporter`` container image has been added and enabled
    by default when kolla_enable_ironic and kolla_enable_prometheus are true
    (following upstream defaults).
