---
features:
  - |
    Created new set of playbooks with name prefix of "secret-store".
    These playbooks merge OpenBao playbooks and Hashicorp Vault
    playbooks.
    By default, the playbooks will deploy OpenBao.
    To use Hashicorp Vault, set ``stackhpc_ca_secret_store: vault``.
