---
features:
  - |
    Merged OpenBao playbooks and Hashicorp Vault playbooks.
    They starts with the prefix "secret-store".
    By default, the playbooks will deploy OpenBao.
    To use Hashicorp Vault, set ``stackhpc_ca_secret_store: vault``.
