---
fixes:
  - |
    Added ``NetworkManager-config-server`` package to Rocky Linux 9 deployment
    image. Which prevents NetworkManager from automatically running DHCP on
    unconfigured ethernet devices and allows connections with static IP
    addresses to be brought up even on ethernet devices with no carrier.
