---
features:
  - |
    Added a new playbook `pulp_sync_publish_promote` that can be used to sync,
    publish and promote all repositories in a single step, as well as sync and
    publish container repos. If you do not want to promote repos then run with
    ``-e repo_promote_production=false``.
