---
upgrade:
  - |
    The ``swap.yml`` custom playbook has been removed in favour of Kayobe's
    support for configuring swap. See the `Kayobe documentation
    <https://docs.openstack.org/kayobe/2024.1/configuration/reference/hosts.html#swap>`__
    for details.
