---
fixes:
  - |
    Fixed RADOS gateway usage exporter deployment failing
    to generate ec2 credentials for the ceph_rgw user.
  - |
    Fixed RADOS gateway usage exporter not using the system
    trust root as its CA bundle.
