---
- hosts: all
  vars:
    script_path: "/home/zuul/src/github.com/stackhpc/stackhpc-kayobe-config/etc/kayobe/environments/ci-tenks/automated-deployment.sh"
  tasks:
    - name: Cat deploy script
      shell:
        cmd: "cat {{ script_path }}"
        executable: /bin/bash

    - name: hostnamectl
      shell:
        cmd: "hostnamectl"
        executable: /bin/bash

    - name: lscpu
      shell:
        cmd: "lscpu"
        executable: /bin/bash

    - name: lsblk
      shell:
        cmd: "lsblk"
        executable: /bin/bash

    - name: free -h
      shell:
        cmd: "free -h"
        executable: /bin/bash

    - name: pwd
      shell:
        cmd: "pwd"
        executable: /bin/bash

    - name: df -h
      shell:
        cmd: "df -h"
        executable: /bin/bash
