---
- name: Set up Sushy Host
  ansible.builtin.import_playbook: ./sushy-1.yml
- name: Create Libvirt vBMC nodes
  ansible.builtin.import_playbook: ./create-virtual-baremetal.yml
- name: Ensure Sushy Emulator is deployed
  ansible.builtin.import_playbook: ./sushy-2.yml
