---
- hosts: localhost
  gather_facts: false

  environment:
    VIRTUAL_ENV: "{{ lookup('env', 'VIRTUAL_ENV') }}"
    KAYOBE_CONFIG_PATH: "{{ lookup('env', 'KAYOBE_CONFIG_PATH') }}"

  tasks:
    - name: Run Sushy 1 playbook
      ansible.builtin.shell: |
          source "$VIRTUAL_ENV/bin/activate"
          kayobe playbook run "$KAYOBE_CONFIG_PATH/environments/stackhpc-sushy-baremetal/ansible/sushy-1.yml"
      args:
        executable: /bin/bash

    - name: Run Create Virtual Baremetal playbook
      ansible.builtin.shell: |
          source "$VIRTUAL_ENV/bin/activate"
          kayobe playbook run "$KAYOBE_CONFIG_PATH/environments/stackhpc-sushy-baremetal/ansible/create-virtual-baremetal.yml"
      args:
        executable: /bin/bash

    - name: Run Sushy 2 playbook
      ansible.builtin.shell: |
          source "$VIRTUAL_ENV/bin/activate"
          kayobe playbook run "$KAYOBE_CONFIG_PATH/environments/stackhpc-sushy-baremetal/ansible/sushy-2.yml"
      args:
        executable: /bin/bash
