# yamllint disable-file
---
# Use prebuilt release train images from Ark.
{% if stackhpc_download_overcloud_host_images | bool %}
download_custom_deploy_image: true
custom_deploy_image_checksum_algorithm: "sha256"
custom_deploy_image_upstream_url: "{{ stackhpc_overcloud_host_image_url }}"
custom_deploy_image_checksum_url: "{{ stackhpc_overcloud_host_image_url }}.sha256"
{% endif %}

# Disable debug logging to avoid generating large log files
ironic_debug: false

# Use prebuilt release train IPA images from Ark.
{% if stackhpc_ipa_image_bifrost_enabled | bool %}
ipa_download_url_username: "{{ stackhpc_release_pulp_username }}"
ipa_download_url_password: "{{ stackhpc_release_pulp_password }}"
ipa_download_force_basic_auth: true
ipa_download_unredirected_headers:
  - Authorization
{% endif %}
