---
path:
  pullrequest: true
  multipleLabelPaths:
    - paths:
        .automation: 'kayobe-automation'
        .automation.conf: 'kayobe-automation'
    - paths:
        doc: 'documentation'
    - paths:
        .github: 'workflows'
        etc:
          kayobe:
            enviromnents:
              ci-aio: 'workflows'
              ci-builder: 'workflows'
              ci-multinode: 'workflows'
            trivy: 'workflows'
        terraform: 'workflows'
        tools:
          scan-images.sh: "workflows"
        tox.ini: 'workflows'
    - paths:
        etc:
          kayobe:
            ansible: 'ansible'
            ansible.cfg: 'ansible'
    - paths:
        etc:
          kayobe:
            kolla:
              config:
                fluentd: "monitoring"
                grafana: "monitoring"
                prometheus: "monitoring"
              inventory:
                group_vars:
                  prometheus-blackbox-exporter: "monitoring"
    - paths:
        etc:
          kayobe:
            kolla:
              kolla-build.conf: "kolla"
            kolla-image-tags.yml: "kolla"
            kolla.yml: "kolla"
        tools:
          kolla-images.py: "kolla"

staleness:
  pullrequest: true
  old: 30
  extraold: 90

requestsize:
  enabled: true
