---
path:
  pullrequest: true
  paths:
    doc: 'documentation'
    .github: 'workflows'
    terraform: 'workflows'
    etc:
      kayobe:
        enviromnents:
          ci-aio: 'workflows'
          ci-builder: 'workflows'
          ci-multinode: 'workflows'
        trivy: 'workflows'
        ansible: 'ansible'
        kolla:
          config:
            grafana: "monitoring"
            prometheus: "monitoring"
            fluentd: "monitoring"

staleness:
  pullrequest: true

requestsize:
  enabled: true
