# This file is a list of path filters for the overcloud host image build workflow in .github/workflows/trigger-overcloud-host-image-build.yml.
pulp-repo-versions: &pulp-repo-versions
  - 'etc/kayobe/pulp-repo-versions.yml'
