# This file is a list of path filters for the PR workflow in .github/workflows/stackhpc-pull-request.yml.
aio:
  - '.automation'
  - '.automation.conf/config.sh'
  - '.automation.conf/tempest/load-lists/default'
  - '.automation.conf/tempest/load-lists/platform.2022.11-test-list.txt'
  - '.automation.conf/tempest/load-lists/refstack-2019.11-test-list.txt'
  - '.automation.conf/tempest/tempest-ci-aio.overrides.conf'
  - '.github/workflows/stackhpc-all-in-one.yml'
  - '.github/workflows/stackhpc-build-kayobe-image.yml'
  - '.github/workflows/stackhpc-pull-request.yml'
  - 'etc/kayobe/*.yml'
  - 'etc/kayobe/ansible/configure-aio-resources.yml'
  - 'etc/kayobe/ansible/growroot.yml'
  - 'etc/kayobe/ansible/requirements.yml'
  - 'etc/kayobe/ansible/scripts/aio-init.sh'
  - 'etc/kayobe/environments/ci-aio/**'
  - 'etc/kayobe/inventory/**'
  - 'etc/kayobe/kolla/**'
  - 'kayobe-env'
  - 'requirements.txt'
  - 'terraform/aio/**'
