# This file is a list of path filters for the PR workflow in .github/workflows/stackhpc-pull-request.yml.
aio:
  - '.automation'
  - '.automation.conf/config.sh'
  - '.automation.conf/tempest/load-lists/default'
  - '.automation.conf/tempest/load-lists/platform.2022.11-test-list.txt'
  - '.automation.conf/tempest/load-lists/refstack-2019.11-test-list.txt'
  - '.automation.conf/tempest/tempest-ci-aio.overrides.conf'
  - '.github/workflows/stackhpc-all-in-one.yml'
  - '.github/workflows/stackhpc-build-kayobe-image.yml'
  - '.github/workflows/stackhpc-pull-request-aio.yml'
  - 'etc/kayobe/**'
  - '!etc/kayobe/ansible/**'
  - 'etc/kayobe/ansible/configure-aio-resources.yml'
  - 'etc/kayobe/ansible/growroot.yml'
  - 'etc/kayobe/ansible/requirements.yml'
  - 'etc/kayobe/ansible/scripts/aio-init.sh'
  - '!etc/kayobe/bifrost.yml'
  - '!etc/kayobe/bmc.yml'
  - '!etc/kayobe/cephadm.yml'
  - '!etc/kayobe/containers/**'
  - '!etc/kayobe/environments/aufn-ceph/**'
  - '!etc/kayobe/environments/ci-builder/**'
  - '!etc/kayobe/environments/ci-multinode/**'
  - '!etc/kayobe/inspector.yml'
  - '!etc/kayobe/ipa.yml'
  - '!etc/kayobe/kolla/config/bifrost/bifrost.yml'
  - '!etc/kayobe/kolla/kolla-build.conf'
  - '!etc/kayobe/overcloud-dib.yml'
  - '!etc/kayobe/seed*'
  - '!etc/kayobe/stackhpc-overcloud-dib.yml'
  - '!etc/kayobe/stackhpc-overcloud-host-images.yml'
  - '!etc/kayobe/vault.yml'
  - 'kayobe-env'
  - 'requirements.txt'
  - 'terraform/aio/**'
