
include: .gitlab/prelude.yml

# TODO:
# - Use https://docs.gitlab.com/ee/ci/environments/#deployment-tier-of-environments
#   instead of environment names
#     - NOTE: This variable is not available in rules, but we can use a variable
#       in a similar way to KAYOBE_ENVIRONMENT, see:
#       https://gitlab.com/gitlab-org/gitlab/-/issues/35315
#     - We might want to allow service deploy to happen in PR to staging but not main?

build kayobe:
  extends:
    - .environment-prepare
    - .dind-tags
  image: docker:stable
  rules:
    - when: always
  services:
    - name: docker:dind
      command: ["--mtu=1450"]
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA && exit 0 || true
    # Set up ssh-agent to login into private kayobe repo
    # - .automation/utils/kayobe-automation-ssh-agent
    # If we've already built it, save some time and don't build it again
    - DOCKER_BUILDKIT=1 docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f .automation/docker/kayobe/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

kolla diff:
  extends:
    - .environment-prepare
    - .tags
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - if: '$CI_MERGE_REQUEST_ID && $KAYOBE_ENVIRONMENT == "builder"'
      variables:
        # Do config-diff on the AIO
        GITLAB_ENVIRONMENT: aio
        KAYOBE_ENVIRONMENT: aio
    - if: $CI_MERGE_REQUEST_ID
  script:
    - .automation/pipeline/config-diff.sh origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - cp /tmp/kayobe-config-diff ${CI_PROJECT_DIR}/kayobe-config-diff.txt
  artifacts:
    expose_as: 'kayobe config diff'
    paths: ['./kayobe-config-diff.txt']

all-in-one:
  stage: run
  trigger:
    include: .gitlab/aio.yml
    strategy: depend
  rules:
    - if: '$KAYOBE_ENVIRONMENT == "aio"'

test:
  stage: run
  trigger:
    include: .gitlab/end-to-end.yml
    strategy: depend
  rules:
    - if: '$CI_MERGE_REQUEST_ID && $KAYOBE_ENVIRONMENT == "builder"'
      variables:
        # Do config-diff on the AIO
        GITLAB_ENVIRONMENT: review/$CI_COMMIT_REF_NAME
        KAYOBE_ENVIRONMENT: aio
    - when: never

overcloud:
  stage: run
  trigger:
    include: .gitlab/overcloud.yml
    strategy: depend
  rules:
    - if: '$KAYOBE_ENVIRONMENT == "builder"'
      when: never
    - if: '$CI_COMMIT_REF_PROTECTED != "true" && $KAYOBE_ENVIRONMENT != "aio"'
      when: never
    - when: always

tempest:
  stage: run
  trigger:
    include: .gitlab/tempest.yml
    strategy: depend
  rules:
    - if: '$KAYOBE_ENVIRONMENT == "builder"'
      when: never
    - if: '$CI_COMMIT_REF_PROTECTED != "true" && $KAYOBE_ENVIRONMENT != "aio"'
      when: never
    - when: always

build:
  stage: run
  trigger:
    include: .gitlab/build.yml
    strategy: depend
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $KAYOBE_ENVIRONMENT == "builder"'
