
include: .gitlab/prelude.yml

build kayobe:
  extends:
    - .tags
  image: docker:stable
  rules:
    - when: always
  services:
    - name: docker:dind
      command: ["--mtu=1450"]
  stage: build
  script:
    - cd .automation/docker/kayobe
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

kolla diff:
  extends:
    - .tags
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - .automation/pipeline/config-diff.sh origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - cp /tmp/kayobe-config-diff ${CI_PROJECT_DIR}/kayobe-config-diff.txt
  artifacts:
    expose_as: 'kayobe config diff'
    paths: ['./kayobe-config-diff.txt']

terraform:
  stage: run
  trigger:
    include: .gitlab/terraform.yml
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^dev\//'

kayobe:
  stage: run
  trigger:
    include: .gitlab/kayobe.yml
    strategy: depend

tempest:
  stage: run
  trigger:
    include: .gitlab/tempest.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_REF_PROTECTED
      when: manual

kayobe custom playbooks:
  stage: run
  trigger:
    include: .gitlab/kayobe-custom-playbooks.yml
    strategy: depend
