---
- name: Check baremetal node bmc is up
  hosts: baremetal
  gather_facts: false
  max_fail_percentage: >-
    {{ baremetal_compute_register_max_fail_percentage |
       default(baremetal_compute_max_fail_percentage) |
       default(kayobe_max_fail_percentage) |
       default(100) }}
  tags:
    - baremetal
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
    controller_host: "{{ groups['controllers'][0] }}"

  tasks:
    - name: Show and check baremetal node
      delegate_to: "{{ controller_host }}"
      vars:
        # NOTE: Without this, the controller's ansible_host variable will not
        # be respected when using delegate_to.
        ansible_host: "{{ hostvars[controller_host].ansible_host | default(controller_host) }}"
        agent_inspect_timeout: "{{ 60 * 20 }}"  # 20 minutes
      environment: "{{ openstack_auth_env }}"
      block:

        - name: Show baremetal node
          ansible.builtin.command:
            cmd: "{{ venv }}/bin/openstack baremetal node show {{ inventory_hostname }} -f json"
          register: node_show
          failed_when:
            - node_show.rc != 0
          changed_when: false

        - name: Check BMC is up
          ansible.builtin.uri:
            url: "{{ ironic_redfish_address + '/redfish/v1' }}"
            method: GET
            status_code: 200
            validate_certs: false
            timeout: 10

        - name: Check for agent inspection details
          ansible.builtin.set_fact:
            kayobe_agent_inspect_done: "{{ (node_show.stdout | from_json)['extra'].get('kayobe_agent_inspect_done') }}"
            inspect_interface: "{{ (node_show.stdout | from_json)['inspect_interface'] }}"
            network_interface: "{{ (node_show.stdout | from_json)['network_interface'] }}"
            provision_state: "{{ (node_show.stdout | from_json)['provision_state'] }}"

        - name: Output when agent inspection was done
          ansible.builtin.debug:
            msg: "{{ inventory_hostname }} inspected at {{ kayobe_agent_inspect_done }}."
          when: kayobe_agent_inspect_done != ""

        - name: Fail if not in manageable state
          ansible.builtin.fail:
            msg: "{{ inventory_hostname }} has the wrong provision_state: {{ provision_state }}"
          when:
            - provision_state not in ["manageable", "inspect failed"]
            - kayobe_agent_inspect_done == ""

        - name: If we failed inspect, move back to managable
          ansible.builtin.command:
            cmd: |
              {{ venv }}/bin/openstack baremetal node manage {{ inventory_hostname }} --wait 300
          register: node_set
          failed_when:
            - node_set.rc != 0
          changed_when: true
          when:
            - provision_state == "inspect failed"
            - kayobe_agent_inspect_done == ""

        - name: Move to agent inspect interface
          ansible.builtin.command:
            cmd: |
              {{ venv }}/bin/openstack baremetal node set {{ inventory_hostname }} --inspect-interface agent
          register: node_set
          failed_when:
            - node_set.rc != 0
          changed_when: true
          when:
            - kayobe_agent_inspect_done == ""
            - inspect_interface == "redfish"

        - name: Ensure we using the flat network interface and correct network
          ansible.builtin.command:
            cmd: |
              {{ venv }}/bin/openstack baremetal node set {{ inventory_hostname }} --network-interface flat --driver-info inspection_network={{ ironic_flat_provisioning_network }} --driver-info cleaning_network={{ ironic_flat_provisioning_network }} --driver-info provision_network={{ ironic_flat_provisioning_network }}
          register: node_set
          failed_when:
            - node_set.rc != 0
          changed_when: true
          when:
            - kayobe_agent_inspect_done == ""

        - name: Wait for inspection
          ansible.builtin.command:
            cmd: |
              {{ venv }}/bin/openstack baremetal node inspect {{ inventory_hostname }} --wait {{ agent_inspect_timeout }}
          register: node_inspect
          failed_when:
            - node_inspect.rc != 0
          changed_when: true
          when: kayobe_agent_inspect_done == ""

        - name: Note when agent inspection is done
          ansible.builtin.command:
            cmd: |
              {{ venv }}/bin/openstack baremetal node set {{ inventory_hostname }} --extra kayobe_agent_inspect_done={{ now(utc=true, fmt='%Y-%m-%dT%H:%M:%SZ') }}
          register: node_set
          failed_when:
            - node_set.rc != 0
          changed_when: true
          when: kayobe_agent_inspect_done == ""
