# yamllint disable-file
---
# Don't build an IPA deployment image, instead download upstream images.
create_ipa_image: false
download_ipa: true

# Use a locally hosted cloud image.
use_cirros: true
{% if os_distribution == 'ubuntu' %}
cirros_deploy_image_upstream_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
{% else %}
cirros_deploy_image_upstream_url: "https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2"
{% endif %}
