---
switch_config: "{{ switch_config_nested | flatten }}"

# Override this for each switch group.
switch_config_nested: []

# Management switch doesn't seem to support PVRST, possibly due to Cumulus 5.2?
# Use RSTP for now, consider switching to pvrst later.
switch_config_stp_mode: rstp

switch_config_system: |
  - set system hostname {{ inventory_hostname }}
  - set system timezone {{ timezone }}
  {% if switch_config_stp_mode == 'pvrst' %}
  # Required for PVRST
  - set system control-plane policer rpvst rate 7200
  - set system control-plane policer rpvst burst 7200
  {% endif %}

switch_config_service: |
  - unset service ntp
  {% for ntp_server in switch_config_ntp_servers %}
  - set service ntp mgmt server {{ ntp_server }} iburst on
  {% endfor %}

switch_config_ntp_servers:
  - "{{ provision_oc_net_name | net_ip(inventory_hostname=groups['seed'][0]) }}"

switch_config_bridge: |
  - unset bridge domain br_default
  {% for vlan in switch_config_vlans | default([]) %}
  - set bridge domain br_default vlan {{ vlan | net_vlan }}
  {% endfor %}
  {% if 'hs-switches' in group_names %}
  - set bridge domain br_default vlan {{ provider_vlans_physnet1.start }}-{{ provider_vlans_physnet1.end }}
  {% endif %}
  {% if switch_config_stp_mode == 'pvrst' %}
  - set bridge domain br_default stp mode pvrst
  {% endif %}

switch_config_mlag:
  # FIXME: MAC (same across both)
  # OR system global anycast-mac 44:38:39:BE:EF:AA ?
  - set mlag mac-address 00:11:22:33:44:55
  # FIXME: IP (per switch) (optional VRF)
  - set mlag backup 1.2.3.4 vrf mgmt
  - set mlag peer-ip linklocal

switch_config_vrf:
  - set vrf baremetal-provisioning table auto

# Range of provider VLANs for physnet1.
provider_vlans_physnet1:
  start: "{{ kolla_neutron_ml2_network_vlan_ranges[0].range.split(':')[0] | int }}"
  end: "{{ kolla_neutron_ml2_network_vlan_ranges[0].range.split(':')[1] | int }}"
