---
switch_config: "{{ [switch_config_system + switch_config_service + switch_config_bridge] }}"

switch_config_system: |
  set system hostname {{ inventory_hostname }}
  set system timezone {{ timezone }}

switch_config_service: |
  unset service ntp
  {% for ntp_server in switch_config_ntp_servers %}
  set service ntp mgmt server {{ ntp_server }} iburst on
  {% endfor %}

switch_config_ntp_servers:
  - "{{ provision_oc_net_name | net_ip(inventory_hostname=groups['seed'][0]) }}"

switch_config_bridge: |
  unset bridge domain br_default
  {% for vlan in switch_config_vlans | default([]) %}
  set bridge domain br_default vlan {{ vlan | net_vlan }}
  {% endfor %}
