---
global:
  resolve_timeout: 5m
  smtp_require_tls: true

route:
  receiver: 'blackhole'
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'blackhole'

templates: []
