# Redfish metrics for the control plane
scrape_configs:
  - job_name: redfish_cp
    metrics_path: /redfish
    static_configs:
    - targets:
      - 172.23.11.101
      - 172.23.11.102
      - 172.23.11.103
      - 172.23.11.111
      - 172.23.11.112
      - 172.23.11.113
      - 172.23.11.121
      - 172.23.11.122
      - 172.23.11.123
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "{{ hostvars['hb-seed01'].ansible_host }}:9610"  ### the address of the redfish-exporter
    scrape_interval: 5m
    scrape_timeout: 60s
