[DEFAULT]
{# Packages in the latest upstream Ubuntu base image can be ahead of our package repo #}
{# snapshots, so pin to a specific tag. #}
{# This tag should be updated when Ubuntu package repo snapshot versions are changed. #}
{% if kolla_base_distro == 'ubuntu' and kolla_base_distro_version == 'jammy' %}
base_tag = jammy-20240808
{% elif kolla_base_distro == 'ubuntu' and kolla_base_distro_version == 'noble' %}
base_tag = noble-20241118.1
{# Similarly pinning to Rocky 9 minor version used in our repos #}
{% elif kolla_base_distro == 'rocky' %}
base_tag = 9.{{ stackhpc_pulp_repo_rocky_9_minor_version }}
{% endif %}
build_args = {{ (kolla_build_args | default({})).items() | map('join', ':') | join(',') }}

[openstack-base]
type = git
location = https://github.com/stackhpc/requirements
#reference = stackhpc/{{ openstack_release }}
reference = rl9.6

[etcd]
version = 3.5.21
sha256 = amd64:adddda4b06718e68671ffabff2f8cee48488ba61ad82900e639d108f2148501c,arm64:95bf6918623a097c0385b96f139d90248614485e781ec9bee4768dbb6c79c53f

[letsencrypt-lego]
version = v4.23.1
sha256 = amd64:1fd60b1fd59c239bed22719a5de402cb745d1f933540cb1ec196e2c03e6e8882,arm64:1114745108343286d4bff189b4bdee3cba9d07ebcacc673860d91ab951d31e0d