[DEFAULT]
{# Packages in the latest upstream Ubuntu base image can be ahead of our package repo #}
{# snapshots, so pin to a specific tag. #}
{# This tag should be updated when Ubuntu package repo snapshot versions are changed. #}
{% if kolla_base_distro == 'ubuntu' %}
base_tag = noble-20260509.1
{% elif kolla_base_distro == 'rocky' %}
base_tag = 10.{{ stackhpc_pulp_repo_rocky_10_minor_version }}
# NOTE(Alex-Welsh): rpm_setup_config is intentionally left blank to override defaults
rpm_setup_config = 
{% endif %}
build_args = {{ (kolla_build_args | default({})).items() | map('join', ':') | join(',') }}
logs = /tmp/kolla
