[DEFAULT]
{# Packages in the latest upstream Ubuntu base image can be ahead of our package repo #}
{# snapshots, so pin to a specific tag. #}
{# This tag should be updated when Ubuntu package repo snapshot versions are changed. #}
{% if kolla_base_distro == 'ubuntu' %}
base_tag = noble-20260610
apt_preferences = {{ lookup('env', 'KAYOBE_CONFIG_PATH') }}/environments/ci-builder/builder-apt-preferences
{# Similarly pinning to Rocky 9 minor version used in our repos #}
{% elif kolla_base_distro == 'rocky' %}
{% if kolla_base_distro_version == '9' %}
base_tag = 9.{{ stackhpc_pulp_repo_rocky_9_minor_version }}
{% elif kolla_base_distro_version == '10' %}
base_tag = 10.{{ stackhpc_pulp_repo_rocky_10_minor_version }}
{% endif %}
# NOTE(Alex-Welsh): rpm_setup_config is intentionally left blank to override defaults
rpm_setup_config = 
{% endif %}
build_args = {{ (kolla_build_args | default({})).items() | map('join', ':') | join(',') }}

[openstack-base]
type = git
location = https://github.com/stackhpc/requirements
reference = stackhpc/{{ openstack_release }}

[etcd]
version = 3.5.27
sha256 = amd64:0aad9a9e4e0817a021e933f9806a2b2960a62f949ad5a3d6436d8886945cb1bc,arm64:1277309f540c5a0329c428f95455c9f76d24f768c8d28fd2753e891c379053fa

[letsencrypt-lego]
version = v4.23.1
sha256 = amd64:1fd60b1fd59c239bed22719a5de402cb745d1f933540cb1ec196e2c03e6e8882,arm64:1114745108343286d4bff189b4bdee3cba9d07ebcacc673860d91ab951d31e0d

[magnum-conductor-plugin-helm]
version = v4.1.4
sha256 = amd64:70b2c30a19da4db264dfd68c8a3664e05093a361cefd89572ffb36f8abfa3d09,arm64:13d03672be289045d2ff00e4e345d61de1c6f21c1257a45955a30e8ae036d8f1

# TODO: move to kolla_sources in kolla.yml once https://review.opendev.org/c/openstack/kayobe/+/970268 is available
[prometheus-cadvisor]
version = 0.56.2
sha256 = amd64:ad92930f16a2f9da15190675e09eeaceb8fd38637d07a686bb0dd68695f692af,arm64:b7a707379496fd7a7b5d2768c5c494427112f534ba5069f889af28ffe6ad11bb
