---
- name: Build OFED packages
  become: true
  hosts: ofed-builder
  gather_facts: false
  tasks:
    - name: Extend the home logical volume
      community.general.lvol:
        vg: rootvg
        lv: lv_home
        size: +5G
        resize2fs: true

    - name: Extend the temporary logical volume
      community.general.lvol:
        vg: rootvg
        lv: lv_var_tmp
        size: +5G
        resize2fs: true

    - name: Install package dependencies
      ansible.builtin.dnf:
        name:
          - kpartx
          - perl
          - rpm-build
          - automake
          - patch
          - kernel
          - kernel-devel
          - autoconf
          - pciutils
          - kernel-rpm-macros
          - lsof
          - libtool
          - tk
          - gcc-gfortran
          - tcl
          - createrepo
          - cmake-filesystem
          - libnl3-devel
        state: latest
        update_cache: true

    - name: Update the default kernel entry
      ansible.builtin.shell:
        cmd: |
          grubby --set-default /boot/$(rpm -qa kernel-devel | sed 's/kernel-devel/vmlinuz/g')
          grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: Disable noexec in temporary file system
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(exclude=.*)noexec,\*\s*'
        replace: '\1'

    - name: Reboot builder to apply kernel update
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Add DOCA host repository
      ansible.builtin.dnf:
        name: https://developer.nvidia.com/downloads/networking/secure/doca-sdk/DOCA_2.8/doca-host-2.8.0-204000_{{ stackhpc_pulp_doca_ofed_version }}_rhel9{{ stackhpc_pulp_repo_rocky_9_minor_version }}.x86_64.rpm

    - name: Install DOCA extra packages
      ansible.builtin.dnf:
        name: doca-extra

    - name: Create build directory
      ansible.builtin.file:
        path: /home/cloud-user/ofed
        state: directory
        mode: 0777

    - name: Set build directory
      ansible.builtin.lineinfile:
        path: /opt/mellanox/doca/tools/doca-kernel-support
        search_string: 'TMP_DIR=$1'
        line: '    TMP_DIR=/home/cloud-user/ofed'

    - name: Build OFED kernel modules
      ansible.builtin.shell:
        cmd: |
          /opt/mellanox/doca/tools/doca-kernel-support

    - name: Download OFED userspace packages
      ansible.builtin.dnf:
        name: doca-ofed-userspace
        download_only: true
        download_dir: /home/cloud-user/ofed
