---
- name: Build OFED kernel modules
  become: true
  hosts: ofed-builder
  gather_facts: false
  tasks:
    - name: Check whether noexec is enabled for /var/tmp
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: noexec
        state: absent
      changed_when: false
      check_mode: true
      register: result
      failed_when: result.found

    - name: Install package dependencies
      ansible.builtin.dnf:
        name:
          - kpartx
          - perl
          - rpm-build
          - automake
          - patch
          - kernel-devel
          - autoconf
          - pciutils
          - kernel-modules-extra
          - kernel-rpm-macros
          - lsof
          - libtool
          - tk
          - gcc-gfortran
          - tcl
          - createrepo
          - cmake-filesystem
          - libnl3-devel
          - python3-devel
          - doca-extra
        state: latest
        update_cache: true

    - name: Build OFED kernel modules
      ansible.builtin.shell:
        cmd: /opt/mellanox/doca/tools/doca-kernel-support
