---
- name: Deploy Ceph using Cephadm
  any_errors_fatal: true
  gather_facts: true
  hosts: ceph
  tags:
    - cephadm
    - cephadm-deploy
  tasks:
    - import_role:
        name: stackhpc.cephadm.cephadm
