---
- name: Ensure additional Ceph commands are run before post-deployment configuration
  gather_facts: false
  hosts: mons
  become: true
  tags:
    - cephadm
    - cephadm-commands
  tasks:
    - import_role:
        name: stackhpc.cephadm.commands
      vars:
        cephadm_commands: "{{ cephadm_commands_pre | default([]) }}"
