---
- name: Define Ceph CRUSH rules
  gather_facts: false
  hosts: mons
  become: true
  tags:
    - cephadm
    - cephadm-crush-rules
  tasks:
    - import_role:
        name: stackhpc.cephadm.crush_rules
