---
- hosts: mgmt-switches
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: dellos10
    os10_facts: "{{ os10_facts_result.ansible_facts }}"
    output_dir: "{{ lookup('env', 'KAYOBE_CONFIG_PATH') ~ '/inventory/host_vars/' ~  inventory_hostname }}"
  tasks:
    - name: Gather facts
      dellemc.os10.os10_facts:
        provider: "{{ switch_dellos_provider }}"
        gather_subset:
          - interfaces
      register: os10_facts_result

    - name: Ensure host_vars directory exists
      file:
        recurse: true
        path: "{{ output_dir }}"
        state: directory
      delegate_to: localhost

    - name: Create switch facts
      vars:
        facts_to_dump:
          switch_facts_mac: "{{ os10_facts.ansible_net_interfaces['mgmt1/1/1'].macaddress }}"
      copy:
        content: |
          ---
          {{ facts_to_dump | to_nice_yaml }}
        dest: "{{  output_dir ~ '/dellos10-facts.yml' }}"
      notify: Remind to commit
      delegate_to: localhost

  handlers:
    - name: Remind to commit
      debug:
        msg: "Looks like we've got some changes. You might want to consider commiting these."
