---
- name: Remove legacy os_exporter.cfg file
  hosts: network
  tags: os_capacity
  gather_facts: false
  tasks:
    - name: Ensure legacy os_exporter.cfg config file is deleted
      ansible.builtin.file:
        path: /etc/kolla/haproxy/services.d/os_exporter.cfg
        state: absent
      become: true

- name: Deploy os-capacity exporter
  hosts: monitoring
  tags: os_capacity
  gather_facts: false
  tasks:
    - name: Create os-capacity directory
      ansible.builtin.file:
        path: /opt/kayobe/os-capacity/
        state: directory
      when: stackhpc_enable_os_capacity

    - name: Read public-openrc credential file
      ansible.builtin.command:
        cmd: "cat {{ lookup('ansible.builtin.env', 'KOLLA_CONFIG_PATH') }}/public-openrc.sh"
      delegate_to: localhost
      register: credential
      when: stackhpc_enable_os_capacity

    - name: Set facts for admin credentials
      ansible.builtin.set_fact:
        stackhpc_os_capacity_auth_url: "{{ credential.stdout_lines | select('match', '.*OS_AUTH_URL*.') | first | split('=') | last | replace(\"'\",'') }}"
        stackhpc_os_capacity_project_name: "{{ credential.stdout_lines | select('match', '.*OS_PROJECT_NAME*.') | first | split('=') | last | replace(\"'\",'') }}"
        stackhpc_os_capacity_domain_name: "{{ credential.stdout_lines | select('match', '.*OS_PROJECT_DOMAIN_NAME*.') | first | split('=') | last | replace(\"'\",'') }}"
        stackhpc_os_capacity_openstack_region_name: "{{ credential.stdout_lines | select('match', '.*OS_REGION_NAME*.') | first | split('=') | last | replace(\"'\",'') }}"
        stackhpc_os_capacity_openstack_interface: "{{ credential.stdout_lines | select('match', '.*OS_INTERFACE*.') | first | split('=') | last | replace(\"'\",'') }}"
        stackhpc_os_capacity_username: "{{ credential.stdout_lines | select('match', '.*OS_USERNAME*.') | first | split('=') | last | replace(\"'\",'') }}"
        stackhpc_os_capacity_password: "{{ credential.stdout_lines | select('match', '.*OS_PASSWORD*.') | first | split('=') | last | replace(\"'\",'') }}"
      when: stackhpc_enable_os_capacity

    - name: Template clouds.yml
      ansible.builtin.template:
        src: templates/os_capacity-clouds.yml.j2
        dest: /opt/kayobe/os-capacity/clouds.yaml
      when: stackhpc_enable_os_capacity

    - name: Ensure os_capacity container is running
      community.docker.docker_container:
        name: os_capacity
        image: ghcr.io/stackhpc/os-capacity:master
        env:
          OS_CLOUD: openstack
          OS_CLIENT_CONFIG_FILE: /etc/openstack/clouds.yaml
        mounts:
          - type: bind
            source: /opt/kayobe/os-capacity/
            target: /etc/openstack/
        network_mode: host
        restart_policy: unless-stopped
      become: true
      when: stackhpc_enable_os_capacity
