---
- name: Login to docker registry
  gather_facts: false
  hosts: container-image-builders
  tasks:
    - name: Login to docker registry
      docker_login:
        registry_url: "{{ kolla_docker_registry or omit }}"
        username: "{{ kolla_docker_registry_username }}"
        password: "{{ kolla_docker_registry_password }}"
        reauthorize: yes
