---
# Custom playbook to generate secrets used by stackhpc-kayobe-config. This
# will template out a file that is used as extra-vars when running kayobe.
# Although the playbook will not update the secrets if they already exist,
# you will need to vault encrypt the file each time you run this playbook.
# It is not mandatory to use this playbook; you are still free to set these
# variables by whatever means you like.
#
# Variables:
# * secrets_path: Where to output the generate secrets. Default is a file
#                 named stackhpc-secrets.yml in your kayobe environment.

- hosts: localhost
  gather_facts: false
  vars:
    secrets_path: "{{ kayobe_env_config_path ~ '/stackhpc-secrets.yml' }}"
  tasks:
    - name: Include existing secrets if they exist
      include_vars: "{{ secrets_path }}"
      when: secrets_path is  exists

    - name: Template new secrets
      template:
        src: stackhpc-secrets.yml.j2
        dest: "{{ secrets_path }}"
