---
# This playbook is designed to be used by the overcloud-host-image-build.yml
# GitHub workflow to upload newly-built images to a development cloud for
# testing and use in CI.
- name: Upload an OS image to Glance
  hosts: seed
  vars:
    local_image_path: "/opt/kayobe/images/overcloud-{{ os_distribution }}-{{ os_release }}/overcloud-{{ os_distribution }}-{{ os_release }}.qcow2"
    image_name: "overcloud-{{ os_distribution }}-{{ os_release }}"
  tasks:
    - block:
        - name: Write out clouds.yaml
          copy:
            content: "{{ lookup('ansible.builtin.env', 'CLOUDS_YAML') }}"
            dest: clouds.yaml
            mode: 0600

        - name: Write out secure.yaml
          no_log: true
          vars:
            os_secrets:
              clouds:
                openstack:
                  auth:
                    application_credential_id: "{{ lookup('ansible.builtin.env', 'OS_APPLICATION_CREDENTIAL_ID') }}"
                    application_credential_secret: "{{ lookup('ansible.builtin.env', 'OS_APPLICATION_CREDENTIAL_SECRET') }}"
          copy:
            content: "{{ os_secrets | to_nice_yaml }}"
            dest: secure.yaml
            mode: 0600

        - name: Ensure dependencies are installed
          pip:
            name: python-openstackclient
            virtualenv: "{{ ansible_python_interpreter | dirname | dirname }}"

        - name: Upload an image to Glance
          openstack.cloud.image:
            cloud: openstack
            name: "{{ image_name }}"
            container_format: bare
            disk_format: qcow2
            state: present
            filename: "{{ local_image_path }}"
            # FIXME: Uncomment this when we have a newer openstack.cloud collection
            #visibility: shared
          register: image

        # FIXME: Remove this when we have a newer openstack.cloud collection
        - name: Make the image shared
          command: openstack image set --shared {{ image.image.id }}

        # Allow users in stackhpc-dev to use these images.
        - name: Add image to stackhpc-dev project
          command: openstack image add project {{ image.image.id }} 2fbf511968aa443e883a82283b0f0160

        # FIXME: This needs to be done when authenticated in the stackhpc-dev
        # project, but we don't have an app cred for this. It must be done
        # manually for now.
        # - name: Accept image membership in stackhpc-dev project
        #   command: openstack image set {{ image.image.id }} --accept

        - name: Display how to add the image to the stackhpc-dev project
          debug:
            msg: |-
              The {{ image_name }} image has been shared with the stackhpc-dev
              project but it must be accepted by a user authenticated in the
              stackhpc-dev project before it can be used there. This can be
              done using the following command:

              openstack image add project {{ image.image.id }} stackhpc-dev

      always:
        - name: Remove clouds.yaml
          file:
            path: clouds.yaml
            state: absent

        - name: Remove secure.yaml
          file:
            path: secure.yaml
            state: absent
