---
- name: Download an overcloud host image from Ark
  hosts: localhost
  vars:
    # This var is an edited version of stackhpc_overcloud_host_image_url
    # without the auth credentials in it. Auth is handled by username and
    # password in the get_url task of this playbook
    stackhpc_overcloud_host_image_url_no_auth: "{{ stackhpc_release_pulp_content_url }}/kayobe-images/\
      {{ openstack_release }}/{{ os_distribution }}/{{ os_release }}/\
      {{ 'ofed/' if stackhpc_overcloud_host_image_is_ofed else '' }}\
      {{ stackhpc_overcloud_host_image_version }}/\
      overcloud-{{ os_distribution }}-{{ os_release }}\
      {{ '-ofed' if stackhpc_overcloud_host_image_is_ofed else '' }}.qcow2"

  tasks:
    - name: Print image information
      debug:
        msg: |
          OS Distribution: {{ os_distribution }}
          OS Release: {{ os_release }}
          Image tag: {{ stackhpc_overcloud_host_image_version }}
          OFED: {{ stackhpc_overcloud_host_image_is_ofed }}

    # TODO: Add checksum support
    - name: Download image artifact
      get_url:
        url: "{{ stackhpc_overcloud_host_image_url_no_auth }}"
        username: "{{ stackhpc_image_repository_username }}"
        password: "{{ stackhpc_image_repository_password }}"
        force_basic_auth: true
        unredirected_headers:
          - "Authorization"
        dest: "/tmp/{{ os_distribution }}-{{ os_release }}.qcow2"
        mode: "0644"
      register: image_download_result
      until: image_download_result.status_code == 200
      retries: 3
      delay: 60
