---
- name: Sync client Pulp container repositories
  hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: stackhpc.pulp.pulp_repository
      # NOTE: use intermediate variable to avoid syncing RPMs.
      vars:
        pulp_repository_container_repos: "{{ stackhpc_pulp_repository_container_repos }}"
