---
- name: Sync Pulp repositories
  hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: stackhpc.pulp.pulp_repository
      # NOTE: use intermediate variable to avoid syncing containers.
      vars:
        pulp_repository_deb_repos: "{{ stackhpc_pulp_repository_deb_repos | selectattr('required') }}"
        pulp_repository_rpm_repos: "{{ stackhpc_pulp_repository_rpm_repos | selectattr('required') }}"
