---
- name: Upload and create a distribution for an image
  hosts: localhost
  vars:
    remote_pulp_url: "{{ stackhpc_release_pulp_url }}"
    remote_pulp_username: "{{ stackhpc_image_repository_username }}"
    remote_pulp_password: "{{ stackhpc_image_repository_password }}"
    repository_name: "kayobe-images-{{ openstack_release }}-{{ os_distribution }}-{{ os_release }}"
    base_path: "kayobe-images/{{ openstack_release }}/{{ os_distribution }}/{{ os_release }}"
  tasks:
    - name: Print image tag
      debug:
        msg: "Image tag: {{ host_image_tag }}"

    - name: Get filename
      find:
        paths: "{{ image_path }}"
        patterns: '*.qcow2'
      register: found_files

    - name: Upload an artifact
      pulp.squeezer.artifact:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        file: "{{ found_files.files[0].path }}"
        state: present
      register: upload_result
      until: upload_result is success
      retries: 3
      delay: 1

    - name: Get sha256 hash
      ansible.builtin.stat:
        path: "{{ found_files.files[0].path }}"
        checksum_algorithm: sha256
      register: file_stats

    - name: Create file content from artifact
      pulp.squeezer.file_content:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        sha256: "{{ file_stats.stat.checksum }}"
        relative_path: "{{ found_files.files[0].path | basename }}"
        state: present
      register: file_content_result
      until: file_content_result is success
      retries: 3
      delay: 1

    - name: Ensure file repo exists
      pulp.squeezer.file_repository:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        name: "{{ repository_name }}"
        state: present
      register: file_repo_result
      until: file_repo_result is success
      retries: 3
      delay: 1

    - name: Add content to file repo
      pulp.squeezer.file_repository_content:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        repository: "{{ repository_name }}"
        present_content:
          - relative_path: "{{ found_files.files[0].path | basename }}"
            sha256: "{{ file_stats.stat.checksum }}"
      register: file_repo_content_result
      until: file_repo_content_result is success
      retries: 3
      delay: 1

    - name: Create a new publication to point to this version
      pulp.squeezer.file_publication:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        repository: "{{ repository_name }}"
        state: present
      register: publication_details
      until: publication_details is success
      retries: 3
      delay: 1

    - name: Update distribution for latest version
      pulp.squeezer.file_distribution:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        name: "{{ repository_name }}_latest"
        base_path: "{{ base_path }}/latest"
        publication: "{{ publication_details.publication.pulp_href }}"
        content_guard: development
        state: present
      register: latest_distribution_details
      until: latest_distribution_details is success
      retries: 3
      delay: 1

    - name: Create distribution for given version
      pulp.squeezer.file_distribution:
        pulp_url: "{{ remote_pulp_url }}"
        username: "{{ remote_pulp_username }}"
        password: "{{ remote_pulp_password }}"
        name: "{{ repository_name }}_{{ host_image_tag }}"
        base_path: "{{ base_path }}/{{ host_image_tag }}"
        publication: "{{ publication_details.publication.pulp_href }}"
        content_guard: development
        state: present
      when: latest_distribution_details.changed
      register: distribution_result
      until: distribution_result is success
      retries: 3
      delay: 1

    - name: Update new images file with versioned path
      lineinfile:
        path: /tmp/updated_images.txt
        line: "{{ remote_pulp_url }}/pulp/content/{{ base_path }}/\
        {{ host_image_tag }}/{{ found_files.files[0].path | basename }}"
        create: true

    - name: Update new images file with latest path
      lineinfile:
        path: /tmp/updated_images.txt
        line: "{{ remote_pulp_url }}/pulp/content/{{ base_path }}/\
        latest/{{ found_files.files[0].path | basename }}"
      when: latest_distribution_details.changed

    - name: Print versioned path
      debug:
        msg: "New versioned path: {{ remote_pulp_url }}/pulp/content/{{ base_path }}/\
        {{ host_image_tag }}/{{ found_files.files[0].path | basename }}"
      when: latest_distribution_details.changed

    - name: Print latest path
      debug:
        msg: "New latest path: {{ remote_pulp_url }}/pulp/content/{{ base_path }}/\
        latest/{{ found_files.files[0].path | basename }}"
      when: latest_distribution_details.changed

    - name: Print version tag
      debug:
        msg: "New tag: {{ host_image_tag }}"
      when: latest_distribution_details.changed
