---
- name: Promote development Pulp repositories to production
  hosts: localhost
  gather_facts: True
  tasks:
    - import_role:
        name: stackhpc.pulp.pulp_distribution
      vars:
        pulp_distribution_rpm: "{{ stackhpc_pulp_distribution_rpm_production }}"
