---
- name: Reboot the host
  hosts: seed-hypervisor:seed:overcloud:infra-vms
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') | default(1, true) }}"
  tags:
    - reboot
  vars:
    reboot_timeout_s: "{{ 20 * 60 }}"
  tasks:
    - name: Reboot and wait
      become: true
      reboot:
        reboot_timeout: "{{ reboot_timeout_s }}"
        search_paths:
          # Systems running molly-guard hang waiting for confirmation before rebooting without this.
          - "/lib/molly-guard"
          # Default list:
          - "/sbin"
          - "/bin"
          - "/usr/sbin"
          - "/usr/bin"
          - "/usr/local/sbin"
