---
- name: Reboot the host
  hosts: seed-hypervisor:seed:overcloud:infra-vms
  serial: "{{ lookup('env', 'ANSIBLE_SERIAL') | default(0, true) }}"
  tags:
    - reboot
  tasks:
    - name: Reboot and wait
      become: true
      reboot:
