---
collections:
  - name: stackhpc.cephadm
    version: 1.22.1
  - name: pulp.squeezer
    version: 0.3.0
  - name: stackhpc.pulp
    version: 0.6.0
  - name: stackhpc.hashicorp
    version: 2.8.2
  - name: stackhpc.kayobe_workflows
    version: 1.2.0
roles:
  - src: stackhpc.vxlan
    version: 1.1.0
  - name: ansible-lockdown.ubuntu24_cis
    src: https://github.com/ansible-lockdown/UBUNTU24-CIS
    version: 1.0.4
  - name: ansible-lockdown.rhel9_cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: v1.3.4
  - name: ansible-lockdown.rhel10_cis
    src: https://github.com/ansible-lockdown/RHEL10-CIS
    version: 1.0.2
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc-v4.10.0
  - name: geerlingguy.pip
    version: 3.1.0
  - name: monolithprojects.github_actions_runner
    src: https://github.com/MonolithProjects/ansible-github_actions_runner
    version: 1.25.1
  - name: geerlingguy.docker
    version: 7.9.0
    # (jackhodgkiss) Update once patch is merged and released upstream.
  - src: https://github.com/stackhpc/ansible-gitlab-runner
    name: riemers.gitlab-runner
    version: use-ansible-facts
