---
# Custom playbook to reset Boot Loader Specification (BLS) entries to resolve
# an issue with GRUB defaulting to an old kernel. This is adapted from a Bash
# script in diskimage-builder:
# https://opendev.org/openstack/diskimage-builder/src/branch/master/diskimage_builder/elements/rhel/post-install.d/03-reset-bls-entries

- name: Reset BLS entries
  hosts: overcloud
  become: true
  tags:
    - reset-bls-entries
  tasks:
    - name: Get machine ID
      command: cat /etc/machine-id
      register: machine_id
      check_mode: false

    - name: Find entries with wrong machine ID
      ansible.builtin.find:
        paths: /boot/loader/entries
        patterns: "*.conf"
      register: bls_entries
      check_mode: false

    # We set force to false to avoid replacing an existing BLS entry with the
    # correct machine ID.
    - name: Rename entries with wrong machine ID
      copy:
        src: "/boot/loader/entries/{{ item }}"
        dest: "/boot/loader/entries/{{ item | ansible.builtin.regex_replace('^[a-f0-9]*', machine_id.stdout) }}"
        force: false
        remote_src: true
      with_items: "{{ bls_entries.files | map(attribute='path') | reject('search', machine_id.stdout) | map('basename') }}"

    - name: Remove entries with wrong machine ID
      file:
        path: "/boot/loader/entries/{{ item }}"
        state: absent
      with_items: "{{ bls_entries.files | map(attribute='path') | reject('search', machine_id.stdout) | map('basename') }}"
