---
- hosts: overcloud

  tasks:
    - name: Ensure smartmon-tools, jq, nvme-cli and cron/cronie is installed
      package:
        name:
          - smartmontools
          - nvme-cli
          - jq
          - "{{ 'cron' if ansible_facts['distribution'] == 'Ubuntu' else 'cronie' }}"
        state: present
      become: true

    - name: Copy smartmon.sh and nvmemon.sh from scripts folder
      copy:
        src: "scripts/{{ item }}"
        dest: /usr/local/bin/
        owner: 'root'
        group: 'root'
        mode: '0700'
      loop:
        - smartmon.sh
        - nvmemon.sh
      become: yes

    - name: Set PATH Variable for cron
      cron:
        name: PATH
        user: root
        env: yes
        job: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      become: yes

    - name: Schedule cronjob to run both scripts every 5 minutes and save output to file
      cron:
        name: "SMART metrics for drive monitoring using {{ item }}"
        user: root
        minute: "*/5"
        job: "/usr/local/bin/{{ item }}.sh > /var/lib/docker/volumes/textfile/_data/{{ item }}.prom.temp && mv -f /var/lib/docker/volumes/textfile/_data/{{ item }}.prom.temp /var/lib/docker/volumes/textfile/_data/{{ item }}.prom"
      loop:
        - smartmon
        - nvmemon
      become: yes
