---
- name: Run StackHPC Cloud tests
  hosts: tempest_runner
  tags:
    - stackhpc-cloud-tests
  vars:
    sct_venv: "{{ virtualenv_path }}/sct-venv"
    sct_repo: https://github.com/stackhpc/stackhpc-cloud-tests
    sct_version: main
    sct_timeout: 30
    results_path_local: "{{ lookup('env', 'HOME') }}/sct-results"
  tasks:
    - name: Stackhpc Cloud tests
      block:
        - name: Create a temporary directory for tests repo
          ansible.builtin.tempfile:
            state: directory
            suffix: sct-repo
          register: repo_tmpdir

        - name: Create a temporary directory for results
          ansible.builtin.tempfile:
            state: directory
            suffix: sct-results
          register: results_tmpdir

        - name: Clone the StackHPC Cloud tests repository
          ansible.builtin.git:
            repo: "{{ sct_repo }}"
            version: "{{ sct_version }}"
            dest: "{{ repo_tmpdir.path }}"
            depth: 1
            single_branch: true

        - name: Ensure the latest versions of pip and setuptools are installed # noqa package-latest
          ansible.builtin.pip:
            name: "{{ item.name }}"
            state: latest
            virtualenv: "{{ sct_venv }}"
            virtualenv_command: python3 -m venv
          with_items:
            - { name: pip }
            - { name: setuptools }

        - name: Ensure required individual Python packages are installed
          ansible.builtin.pip:
            name:
              - "{{ repo_tmpdir.path }}"
              - pytest-html
              - pytest-timeout
            virtualenv: "{{ sct_venv }}"

        - name: Ensure Python requirements file packages are installed
          ansible.builtin.pip:
            requirements: "{{ repo_tmpdir.path }}/requirements.txt"
            virtualenv: "{{ sct_venv }}"

        - name: Include Kolla Ansible passwords
          ansible.builtin.include_vars:
            file: "{{ kayobe_env_config_path }}/kolla/passwords.yml"
            name: kolla_passwords

        - name: Run StackHPC Cloud tests
          ansible.builtin.command:
            cmd: >
              {{ sct_venv }}/bin/py.test
              --html={{ results_tmpdir.path }}/stackhpc-cloud-tests.html
              --self-contained-html
              --pyargs stackhpc_cloud_tests
              --timeout {{ sct_timeout }}
              -rfEx
              -vv
          environment:
            OPENSEARCH_HOSTS: "{{ sct_opensearch_hosts }}"
            OPENSEARCH_PORT: "{{ sct_opensearch_port }}"
            OPENSEARCH_TLS: "{{ sct_opensearch_tls }}"
            PROMETHEUS_URL: "{{ sct_prometheus_url }}"
            PROMETHEUS_USERNAME: "{{ sct_prometheus_username }}"
            PROMETHEUS_PASSWORD: "{{ sct_prometheus_password }}"
          vars:
            kolla_external_scheme: "{{ 'https' if kolla_enable_tls_external | bool else 'http' }}"
            kolla_internal_scheme: "{{ 'https' if kolla_enable_tls_internal | bool else 'http' }}"
            sct_opensearch_hosts: "{{ kolla_internal_fqdn }}"
            sct_opensearch_port: 9200
            sct_opensearch_tls: false
            sct_prometheus_url: "{{ kolla_internal_scheme }}://{{ kolla_internal_fqdn }}:9091"
            sct_prometheus_username: admin
            sct_prometheus_password: "{{ kolla_passwords.prometheus_password }}"
      always:
        - name: Fetch results
          ansible.builtin.fetch:
            src: "{{ results_tmpdir.path }}/stackhpc-cloud-tests.html"
            dest: "{{ results_path_local }}/"
            flat: true

        - name: Clean up temporary directory
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ repo_tmpdir.path }}"
            - "{{ results_tmpdir.path }}"
