---
- name: Migrate hosts from Ubuntu Focal 20.04 to Jammy 22.04
  hosts: overcloud:infra-vms:seed
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    - name: Assert that hosts are running Ubuntu Focal
      assert:
        that:
          - ansible_facts.distribution == 'Ubuntu'
          - ansible_facts.distribution_major_version == '20'
          - ansible_facts.distribution_release == 'focal'
          - os_distribution == 'ubuntu'
        fail_msg: >-
          This playbook is only designed for Ubuntu Focal 20.04 hosts. Ensure
          that you are limiting it to only run on Focal hosts and
          os_distribution in set to ubuntu.

    - name: Ensure apt packages are up to date
      apt:
        update_cache: true
        upgrade: yes

    # NOTE: We cannot use apt_repository here because definitions must exist within the standard repos.list
    - name: Ensure Jammy repo definitions exist in sources.list
      blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb {{ stackhpc_repo_ubuntu_jammy_url }} jammy main restricted universe multiverse
          deb {{ stackhpc_repo_ubuntu_jammy_url }} jammy-updates main restricted universe multiverse
          deb {{ stackhpc_repo_ubuntu_jammy_url }} jammy-backports main restricted universe multiverse
          deb {{ stackhpc_repo_ubuntu_jammy_security_url }} jammy-security main restricted universe multiverse

    - name: Ensure do-release-upgrade is installed
      package:
        name: ubuntu-release-upgrader-core
        state: latest

    - name: Do release upgrade
      command: do-release-upgrade -f DistUpgradeViewNonInteractive

    - name: Print selection of Deities to pray to
      debug:
        msg: |
          The following Deities are associated with luck or good fortune:
            Hamingja - Norse guardian spirit
            Fortuna - Roman goddess of fortune and luck
            Tyche - Greek goddess of success, fortune, Luck, and prosperity
            Nang Kwak - Thai folklore goddess deemed to bring good fortune and prosperity

    - name: Ensure Jammy repo definitions do not exist in sources.list
      blockinfile:
        path: /etc/apt/sources.list
        state: absent
        block: |
          deb {{ stackhpc_repo_ubuntu_jammy_url }} jammy main restricted universe multiverse
          deb {{ stackhpc_repo_ubuntu_jammy_url }} jammy-updates main restricted universe multiverse
          deb {{ stackhpc_repo_ubuntu_jammy_url }} jammy-backports main restricted universe multiverse
          deb {{ stackhpc_repo_ubuntu_jammy_security_url }} jammy-security main restricted universe multiverse

    - name: Ensure old venvs do not exist
      file:
        path: "/opt/kayobe/venvs/{{ item }}"
        state: absent
      loop:
        - kayobe
        - kolla-ansible

    - name: debug
      debug: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}/share/kayobe/ansible/network.yml"

    - name: Run kayobe-target-venv playbook to ensure kayobe venv exists on remote host
      import_playbook: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}/share/kayobe/ansible/kayobe-target-venv.yml"

    - name: Run network playbook to ensure networking config is not reliant on ifupdown
      import_playbook: "{{ lookup('ansible.builtin.env', 'VIRTUAL_ENV') }}/share/kayobe/ansible/network.yml"

    - name: Reboot and wait
      reboot:

    - name: Gather facts
      gather_facts:

    - name: Assert that hosts are now using Ubuntu 22
      assert:
        that:
          - ansible_facts.distribution_major_version == '22'
          - ansible_facts.distribution_release == 'jammy'
