---
    # This playbook uploads MariaDB backups to an AWS S3 object store.
    # Can be linked as a post hook for overcloud-database-backup.

    - hosts: controllers[0]
      vars:
        backup_directory: "/var/lib/docker/volumes/mariadb_backup/_data"
        kayobe_venv: "/opt/kayobe/venvs/kayobe"
      tasks:
        - name: Ensure AWS S3 module prerequisities are available
          pip:
            name:
              - boto3
              - botocore
            virtualenv: "{{ kayobe_venv }}"

        - name: Build backup file list
          find:
            paths: "{{ backup_directory }}"
          become: True
          register: backups

        - name: Upload backup files to S3
          amazon.aws.aws_s3:
            s3_url: "{{ s3_url }}"
            access_key: "{{ secrets_s3_access_key }}"
            secret_key: "{{ secrets_s3_secret_key }}"
            bucket: "{{ s3_mariadb_mysql_backup_bucket }}"
            object: "{{ item.path | basename }}"
            src: "{{ item.path }}"
            mode: put
            overwrite: different
            validate_certs: False
          become: True
          with_items: "{{ backups.files }}"