---
# Required for uri module to work with self-signed certificates and for systems to trust
# the self-signed CA
- name: Install CA on controllers
  hosts: controllers
  tasks:
    - name: Copy the rootCA
      copy:
        src: "{{ kayobe_env_config_path }}/vault/rootCA.crt"
        dest: "{{ '/etc/pki/ca-trust/source/anchors/rootCA.crt' if ansible_facts.os_family == 'RedHat' else '/usr/local/share/ca-certificates/rootCA.crt' }}"
        mode: 0644
      become: true

    - name: update system CA
      become: true
      shell: "{{ 'update-ca-trust' if ansible_facts.os_family == 'RedHat' else 'update-ca-certificates' }}"

- name: Deploy HashiCorp Vault on the overcloud
  any_errors_fatal: true
  gather_facts: true
  hosts: controllers
  vars:
    consul_bind_interface: "{{ internal_net_name | net_interface }}"
    vault_bind_address: "{{ internal_net_name | net_ip }}"
    vault_api_addr: "https://{{ kolla_internal_fqdn }}:8200"
  tasks:
    - name: Set a fact about the virtualenv on the remote system
      set_fact:
        virtualenv: "{{ ansible_python_interpreter | dirname | dirname }}"
      when:
        - ansible_python_interpreter is defined
        - not ansible_python_interpreter.startswith('/bin/')
        - not ansible_python_interpreter.startswith('/usr/bin/')

    - name: Ensure Python hvac module is installed
      pip:
        name: hvac
        state: latest
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"
        virtualenv: "{{ virtualenv is defined | ternary(virtualenv, omit) }}"
      become: "{{ virtualenv is not defined }}"

    - name: Ensure /opt/kayobe/vault exists
      file:
        path: /opt/kayobe/vault
        state: directory

    - name: Template out TLS key and cert
      copy:
        # Within the Hashicorp Vault container these uids & gids map to the vault user
        src: "{{ kayobe_env_config_path }}/vault/{{ item }}"
        dest: "/opt/kayobe/vault/{{ item }}"
        owner: 100
        group: 1000
        mode: 0600
      loop:
        - overcloud.crt
        - overcloud.key
      no_log: true
      become: true

    - import_role:
        name: stackhpc.hashicorp.vault
      vars:
        vault_config_dir: "/opt/kayobe/vault"
        vault_cluster_name: "overcloud"
        vault_tls_cert: "overcloud.crt"
        vault_tls_key: "overcloud.key"
        copy_self_signed_ca: true
        vault_write_keys_file: true
        vault_write_keys_file_path: "{{ kayobe_env_config_path }}/vault/overcloud-vault-keys.json"

    - name: Include Vault keys
      include_vars:
        file: "{{ kayobe_env_config_path }}/vault/overcloud-vault-keys.json"
        name: vault_keys

    - import_role:
        name: stackhpc.hashicorp.vault_unseal
      vars:
        # NOTE: Need to unseal each backend, so don't use the VIP
        vault_api_addr: "http://localhost:8200"
        vault_unseal_keys: "{{ vault_keys.keys_base64 }}"

    - import_role:
        name: stackhpc.hashicorp.vault_backend_ha
      vars:
        vault_token: "{{ vault_keys.root_token }}"
        vault_root_ca_name: "OS-TLS-ROOT"
        vault_intermediate_ca_name: "OS-TLS-INT"
