---
- name: Migrate Overcloud vault to OpenBao
  any_errors_fatal: true
  gather_facts: true
  hosts: controllers
  vars:
    secret_store_bind_interface: "{{ internal_net_name | net_interface }}"
    secret_store_bind_address: "{{ ansible_facts[secret_store_bind_interface].ipv4.address }}"
    secret_store_api_address: "https://{{ secret_store_bind_address }}:8200"
  tasks:
    - name: Set a fact about the virtualenv on the remote system
      ansible.builtin.set_fact:
        virtualenv: "{{ ansible_python_interpreter | dirname | dirname }}"
      when:
        - ansible_python_interpreter is defined
        - not ansible_python_interpreter.startswith('/bin/')
        - not ansible_python_interpreter.startswith('/usr/bin/')

    - name: Ensure Python hvac module is installed
      ansible.builtin.pip:
        name: hvac
        state: latest
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"
        virtualenv: "{{ virtualenv is defined | ternary(virtualenv, omit) }}"
      become: "{{ virtualenv is not defined }}"

    - name: Include secret store keys
      ansible.builtin.include_vars:
        file: "{{ kayobe_env_config_path }}/{{ stackhpc_ca_secret_store }}/overcloud-{{ stackhpc_ca_secret_store }}-keys.json"
        name: secret_store_keys
   
    - name: show group
      debug:
        var: groups["controllers"]
      run_once: true


    - name: Apply vault_bao_migration role
      ansible.builtin.include_role:
        name: stackhpc.hashicorp.vault_bao_migration
      vars:
        consul_docker_image: "{{ overcloud_consul_docker_image }}"
        consul_docker_tag: "{{ overcloud_consul_docker_tag }}"
        consul_bind_interface: "{{ secret_store_bind_interface }}"
        hashicorp_registry_url: "{{ overcloud_hashicorp_registry_url }}"
        hashicorp_registry_username: "{{ overcloud_hashicorp_registry_username }}"
        hashicorp_registry_password: "{{ overcloud_hashicorp_registry_password }}"
        vault_root_token: "{{ secret_store_keys.root_token }}"
        vault_unseal_keys: "{{ secret_store_keys.keys_base64 }}"
        vault_bind_address: "{{ secret_store_bind_address }}"
        vault_api_addr: "https://{{ internal_net_name | net_ip }}:8200"
        vault_config_dir: /opt/kayobe/vault
        vault_cluster_name: overcloud
        vault_docker_image: "{{ overcloud_vault_docker_image }}"
        vault_docker_tag: "{{ overcloud_vault_docker_tag }}"
        vault_write_keys_file: true
        vault_write_keys_file_path: "{{ kayobe_env_config_path }}/vault/overcloud-vault-keys.json"
        vault_tls_cert: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.crt"
        vault_tls_key: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.key"
        vault_unseal_timeout: 10
        openbao_bind_addr: "{{ secret_store_bind_address }}"
        openbao_api_addr: "{{ secret_store_api_address }}"
        openbao_registry_url: "{{ overcloud_openbao_registry_url }}"
        openbao_registry_username: "{{ overcloud_openbao_registry_username }}"
        openbao_registry_password: "{{ overcloud_openbao_registry_password }}"
        openbao_config_dir: /opt/kayobe/openbao
        openbao_cluster_name: overcloud
        openbao_docker_image: "{{ overcloud_openbao_docker_image }}"
        openbao_docker_tag: "{{ overcloud_openbao_docker_tag }}"
        openbao_tls_cert: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.crt"
        openbao_tls_key: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.key"
        openbao_tls_ca: "OS-TLS-INT.crt"
    
- name: Migrate Vault to Openbao
  import_playbook: stackhpc.hashicorp.ha_vault_bao_migration
  vars:
    vault_hosts: "{{ groups['controllers'] }}"
    secret_store_bind_interface: "{{ internal_net_name | net_interface }}"
    secret_store_bind_address: "{{ ansible_facts[secret_store_bind_interface].ipv4.address }}"
    secret_store_api_address: "https://{{ secret_store_bind_address }}:8200"
    vault_root_token: "{{ secret_store_keys.root_token }}"
    vault_unseal_keys: "{{ secret_store_keys.keys_base64 }}"
    vault_bind_address: "{{ secret_store_bind_address }}"
    vault_api_addr: "https://{{ internal_net_name | net_ip }}:8200"
    vault_config_dir: /opt/kayobe/vault
    vault_cluster_name: overcloud
    vault_docker_image: "{{ overcloud_vault_docker_image }}"
    vault_docker_tag: "{{ overcloud_vault_docker_tag }}"
    vault_write_keys_file: true
    vault_write_keys_file_path: "{{ kayobe_env_config_path }}/vault/overcloud-vault-keys.json"
    vault_tls_cert: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.crt"
    vault_tls_key: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.key"
    vault_tls_ca: "OS-TLS-INT.crt"
    vault_unseal_timeout: 10
    openbao_bind_addr: "{{ secret_store_bind_address }}"
    openbao_api_addr: "{{ secret_store_api_address }}"
    openbao_registry_url: "{{ overcloud_openbao_registry_url }}"
    openbao_registry_username: "{{ overcloud_openbao_registry_username }}"
    openbao_registry_password: "{{ overcloud_openbao_registry_password }}"
    openbao_config_dir: /opt/kayobe/openbao
    openbao_cluster_name: overcloud
    openbao_docker_image: "{{ overcloud_openbao_docker_image }}"
    openbao_docker_tag: "{{ overcloud_openbao_docker_tag }}"
    openbao_tls_cert: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.crt"
    openbao_tls_key: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% else %}overcloud{% endif %}.key"
    openbao_tls_ca: "OS-TLS-INT.crt"
