---
- name: Generate vault self-signed certificates
  any_errors_fatal: true
  gather_facts: true
  hosts: seed
  vars:
    vault_bind_address: "{{ ansible_facts['lo'].ipv4.address }}"
    vault_api_addr: "http://{{ vault_bind_address }}:8200"
    vault_intermediate_ca_name: "OS-TLS-INT"
  tasks:
    - name: Include Vault keys
      include_vars:
        file: "{{ kayobe_env_config_path }}/vault/seed-vault-keys.json"
        name: vault_keys

    - name: Issue a certificate for Vault
      hashivault_pki_cert_issue:
        url: "{{ vault_api_addr }}"
        token: "{{ vault_keys.root_token }}"
        mount_point: "{{ vault_intermediate_ca_name }}"
        role: "ServerCert"
        common_name: "{% if kolla_internal_fqdn != kolla_internal_vip_address %}{{ kolla_internal_fqdn }}{% endif %}"
        extra_params:
          ip_sans: "{{ kolla_internal_vip_address }}{% for controller in groups['controllers'] %},{{ internal_net_name | net_ip(inventory_hostname=controller) }}{% endfor %}"
      register: vault_cert

    - name: "Create vault cert for export"
      copy:
        dest: "{{ kayobe_env_config_path }}/vault/overcloud.crt"
        content: |
          {{ vault_cert.data.certificate }}
          {{ vault_cert.data.issuing_ca }}
        mode: '0600'
      delegate_to: localhost

    - name: "Create vault private key for export"
      copy:
        dest: "{{ kayobe_env_config_path }}/vault/overcloud.key"
        content: "{{ vault_cert.data.private_key }}"
        mode: '0600'
      delegate_to: localhost
