---
- hosts: localhost
  gather_facts: false
  vars:
    wazuh_secrets_path: "{{ kayobe_env_config_path }}/wazuh-secrets.yml"
  tasks:
    - name: install passlib[bcrypt]
      pip:
        name: passlib[bcrypt]
        virtualenv: "{{ ansible_playbook_python | dirname | dirname }}"

    - name: Ensure secrets directory exists
      file:
        path: "{{ wazuh_secrets_path | dirname }}"
        state: directory

    - name: Template new secrets
      template:
        src: wazuh-secrets.yml.j2
        dest: "{{ wazuh_secrets_path }}"
      notify: Please encrypt keys

  handlers:
    - name: Please encrypt keys
      debug:
        msg: >-
          Please encrypt the keys using Ansible Vault.
