---
- name: Deploy Wazuh agent
  hosts: wazuh-agent
  become: yes
  tasks:
    - import_role:
        name: "wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-agent"
  post_tasks:
    - name: Check if custom SCA policies directory exists
      stat:
        path: "{{ local_custom_sca_policies_path }}"
      register: custom_sca_policies_folder
      delegate_to: localhost

    - name: Gather list of custom SCA policies
      find:
        paths: "{{ local_custom_sca_policies_path }}"
        patterns: '*.yml'
      delegate_to: localhost
      register: custom_sca_policies
      when: custom_sca_policies_folder.stat.exists

    - name: Allow Wazuh agents to execute commands in SCA policies sent from the Wazuh manager
      become: yes
      blockinfile:
        path: "/var/ossec/etc/local_internal_options.conf"
        state: present
        owner: wazuh
        group: wazuh
        block: sca.remote_commands=1
      when:
        - custom_sca_policies_folder.stat.exists
        - custom_sca_policies.files | length > 0
      notify:
        - Restart wazuh-agent

  handlers:
    - name: Restart wazuh-agent
      service:
        name: wazuh-agent
        state: restarted
