---
- hosts: localhost
  gather_facts: false
  vars:
    wazuh_secrets_path: "{{ kayobe_env_config_path }}/inventory/group_vars/wazuh/wazuh-manager/wazuh-secrets"
  tasks:
    - name: install passlib[bcrypt]
      pip:
        name: passlib[bcrypt]
        virtualenv: "{{ ansible_playbook_python | dirname | dirname }}"

    - name: Include existing secrets if they exist
      include_vars: "{{ wazuh_secrets_path }}"
      ignore_errors: true

    - name: Ensure secrets directory exists
      file:
        path: "{{ wazuh_secrets_path | dirname }}"
        state: directory

    - name: Template new secrets
      template:
        src: wazuh-secrets.yml.j2
        dest: "{{ wazuh_secrets_path }}"
