---
- hosts: localhost
  gather_facts: false
  vars:
    wazuh_secrets_path: "{{ kayobe_env_config_path }}/wazuh-secrets.yml"
  tasks:
    - name: install passlib[bcrypt]
      pip:
        name: passlib[bcrypt]
        virtualenv: "{{ ansible_playbook_python | dirname | dirname }}"

    - name: Ensure secrets directory exists
      file:
        path: "{{ wazuh_secrets_path | dirname }}"
        state: directory

    - name: Check whether wazuh-secrets.yml exists
      stat:
        path: "{{ wazuh_secrets_path }}"
      register: waz_exist_result

    - name: Decrypt wazuh-secrets to checksum
      no_log: True
      copy:
        content: "{{ lookup('ansible.builtin.file', wazuh_secrets_path) | ansible.builtin.vault(ansible_vault_password) }}"
        dest: "{{ wazuh_secrets_path }}"
        decrypt: true
      vars:
        ansible_vault_password: "{{ lookup('ansible.builtin.env', 'KAYOBE_VAULT_PASSWORD') }}"
      when: waz_exist_result.stat.exists

    - name: Template new secrets
      no_log: True
      template:
        src: wazuh-secrets.yml.j2
        dest: "/tmp/wazuh-secrets.yml"
      when: waz_exist_result.stat.exists

    - name: Copy for checksum
      no_log: True
      copy:
        content: "{{ lookup('ansible.builtin.file', '/tmp/wazuh-secrets.yml') }}"
        dest: "{{ wazuh_secrets_path }}"
        checksum: yes
      when: waz_exist_result.stat.exists

    - name: Template new secrets
      no_log: True
      template:
        src: wazuh-secrets.yml.j2
        dest: "{{ wazuh_secrets_path }}"
      when: not waz_exist_result.stat.exists

    - name: In-place encrypt wazuh-secrets
      no_log: True
      copy:
        content: "{{ lookup('ansible.builtin.file', wazuh_secrets_path) | ansible.builtin.vault(ansible_vault_password) }}"
        dest: "{{ wazuh_secrets_path }}"
        decrypt: false
      vars:
        ansible_vault_password: "{{ lookup('ansible.builtin.env', 'KAYOBE_VAULT_PASSWORD') }}"
