---
- hosts: localhost
  gather_facts: false
  vars:
    wazuh_secrets_path: "{{ kayobe_env_config_path }}/wazuh-secrets.yml"
    override_special_characters: '"#$%&()*+,-./:;<=>?@[\]^_{|}~'
  tasks:
    - name: install passlib[bcrypt]
      pip:
        name: passlib[bcrypt]
        virtualenv: "{{ ansible_playbook_python | dirname | dirname }}"

    - name: Ensure secrets directory exists
      file:
        path: "{{ wazuh_secrets_path | dirname }}"
        state: directory

    - name: Template new secrets
      no_log: True
      template:
        src: wazuh-secrets.yml.j2
        dest: "{{ wazuh_secrets_path }}"

    - name: In-place encrypt wazuh-secrets
      copy:
        content: "{{ lookup('ansible.builtin.file', wazuh_secrets_path) | ansible.builtin.vault(ansible_vault_password) }}"
        dest: "{{ wazuh_secrets_path }}"
        decrypt: false
      vars:
        ansible_vault_password: "{{ lookup('ansible.builtin.env', 'KAYOBE_VAULT_PASSWORD') }}"
