---
- name: Write out value of kolla_tag
  hosts: localhost
  gather_facts: no
  vars:
    kolla_tag_dest: ~/kolla_tag
  tasks:
    - name: Query image tag
      command:
        cmd: "awk '$1 ~ \"tag=\" { print substr($1,5) }' {{ kolla_build_config_path }}/kolla-build.conf"
      become: true
      register: tag

    - name: Write out value of kolla_tag
      copy:
        content: "{{ tag.stdout }}"
        dest: "{{ kolla_tag_dest }}"
