---
- name: Write Kayobe Automation Workflows for GitHub
  hosts: github-writer
  vars:
    github_output_directory: "{{ kayobe_config_path }}/../../.github/workflows"
  roles:
    - stackhpc.kayobe_workflows.github
