---
- name: Write out value of kolla_tag
  hosts: localhost
  gather_facts: no
  vars:
    kolla_tag_dest: ~/kolla_tag
  tasks:
    - name: Query image tag
      shell:
        cmd: >-
          grep '^tag' {{ kolla_build_config_path }}/kolla-build.conf |
          sed 's/tag\s=\s\(.*\)/\1/'
      become: true
      register: tag

    - name: Write out value of kolla_tag
      copy:
        content: "{{ tag.stdout }}"
        dest: "{{ kolla_tag_dest }}"
