---
ironic_driver: ipmi

ironic_driver_info:
  ipmi_address: "{{ ironic_ipmi_address }}"
  ipmi_username: "{{ ironic_ipmi_username }}"
  ipmi_password: "{{ ironic_ipmi_password }}"
  ipmi_verify_ca: "{{ ironic_ipmi_verify_ca }}"

ironic_ipmi_verify_ca: false
ironic_ipmi_address: "{{ ipmi_address }}"
ironic_ipmi_username: "{{ secrets_ipmi_baremetal_username }}"
ironic_ipmi_password: "{{ secrets_ipmi_baremetal_password }}"
