---
# Wazuh deployment details and documetation:
# https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/index.html
#
# Defaults that are modified by this file:
# https://github.com/wazuh/wazuh-ansible/blob/4.3/roles/wazuh/ansible-filebeat-oss/defaults/main.yml
# https://github.com/wazuh/wazuh-ansible/blob/4.3/roles/wazuh/ansible-wazuh-manager/defaults/main.yml
# https://github.com/wazuh/wazuh-ansible/blob/4.3/roles/wazuh/wazuh-dashboard/defaults/main.yml
# https://github.com/wazuh/wazuh-ansible/blob/4.3/roles/wazuh/wazuh-indexer/defaults/main.yml
# https://github.com/wazuh/wazuh-ansible/blob/4.3/roles/wazuh/ansible-wazuh-manager/defaults/main.yml

# Ansible control host certificate directory
local_certs_path: "{{ kayobe_env_config_path }}/wazuh/"

# Dashboard variables
dashboard_server_host: "{{ internal_net_name | net_ip }}"

dashboard_node_name: "wazuh-dashboard"
