{% if groups.get('ceph-exporters', []) | length > 0  %}
scrape_configs:
  - job_name: ceph
    static_configs:
      - targets:
{% for host in groups['ceph-exporters'] %}
        - "{{ host }}:9283"
{% endfor %}
    relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance
    scrape_interval: 15s
{% endif %}
