scrape_configs:
- job_name: blackbox_exporter2
  honor_labels: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 10.225.1.1:9115
    action: replace
  static_configs:
  - targets:
    - "https://{{ public_net_fqdn }}/auth/login/"
    - "https://{{ public_net_fqdn }}:5000/v3"
