---
- name: Generate internal API certificate
  hosts: controllers
  run_once: true
  vars:
    secret_store_api_address: "{{ external_vault_api_address }}"
    secret_store_pki_mount_point: "{{ external_vault_pki_mount_point }}"
    secret_store_pki_role_name: "{{ external_vault_pki_role_name }}"
    secret_store_namespace: "{{ external_vault_pki_namespace }}"
  tasks:
    - name: Set a fact about the virtualenv on the remote system
      ansible.builtin.set_fact:
        virtualenv: "{{ ansible_python_interpreter | dirname | dirname }}"
      when:
        - ansible_python_interpreter is defined
        - not ansible_python_interpreter.startswith('/bin/')
        - not ansible_python_interpreter.startswith('/usr/bin/')

    - name: Ensure Python hvac module is installed
      ansible.builtin.pip:
        name: hvac
        state: latest
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"
        virtualenv: "{{ virtualenv is defined | ternary(virtualenv, omit) }}"
      become: "{{ virtualenv is not defined }}"

    - name: Issue a certificate for internal TLS
      hashivault_pki_cert_issue:  # noqa: fqcn
        url: "{{ secret_store_api_address }}"
        ca_cert: "{{ '/etc/pki/tls/certs/ca-bundle.crt' if ansible_facts.os_family == 'RedHat' else '/usr/local/share/ca-certificates/OS-TLS-ROOT.crt' }}"
        token: "{{ secrets_external_vault_token }}"
        mount_point: "{{ secret_store_pki_mount_point }}"
        namespace: "{{ secret_store_namespace }}"
        role: "{{ secret_store_pki_role_name }}"
        common_name: "{{ kolla_internal_fqdn }}"
        extra_params:
          ip_sans: "{{ kolla_internal_vip_address }}"
      register: internal_cert
      environment:
        https_proxy: ""

    - name: Ensure certificates directory exists
      ansible.builtin.file:
        path: "{{ kayobe_env_config_path }}/kolla/certificates"
        state: directory
      delegate_to: localhost

    - name: Ensure CA certificates directory exists
      ansible.builtin.file:
        path: "{{ kayobe_env_config_path }}/kolla/certificates/ca"
        state: directory
      delegate_to: localhost

    - name: Copy internal API PEM bundle
      no_log: true
      ansible.builtin.copy:
        dest: "{{ kayobe_env_config_path }}/kolla/certificates/haproxy-internal.pem"
        content: |
          {{ internal_cert.data.certificate }}
          {{ internal_cert.data.issuing_ca }}
          {{ internal_cert.data.private_key }}
        mode: "0600"
      delegate_to: localhost

    # NOTE(seunghun1ee): Kolla Ansible reuses internal TLS certificate when
    # creating certificate for proxysql
    # https://opendev.org/openstack/kolla-ansible/src/branch/stable/2026.1/ansible/roles/certificates/tasks/generate.yml#L169-L183
    - name: Generate ProxySQL certificates
      when: kolla_enable_proxysql | bool
      block:
        - name: Copy ProxySQL certificate
          no_log: true
          ansible.builtin.copy:
            dest: "{{ kayobe_env_config_path }}/kolla/certificates/proxysql-cert.pem"
            content: |
              {{ internal_cert.data.certificate }}
              {{ internal_cert.data.issuing_ca }}
            mode: "0600"
          delegate_to: localhost

        - name: Copy ProxySQL certificate key
          no_log: true
          ansible.builtin.copy:
            dest: "{{ kayobe_env_config_path }}/kolla/certificates/proxysql-key.pem"
            content: |
              {{ internal_cert.data.private_key }}
            mode: "0600"
          delegate_to: localhost
