---
- name: Get current OpenBao Raft leader
  import_playbook: get-current-raft-leader.yml

- name: Run deploy playbook with the current raft_leader_index set
  import_playbook: secret-store-deploy-overcloud.yml
