---
- name: Deploy CA secret store on the seed
  any_errors_fatal: true
  gather_facts: true
  hosts: seed
  vars:
    secret_store_bind_interface: lo
    secret_store_bind_address: "{{ ansible_facts[secret_store_bind_interface].ipv4.address }}"
    secret_store_api_address: "http://{{ secret_store_bind_address }}:8200"
  tasks:
    - name: Set a fact about the virtualenv on the remote system
      ansible.builtin.set_fact:
        virtualenv: "{{ ansible_python_interpreter | dirname | dirname }}"
      when:
        - ansible_python_interpreter is defined
        - not ansible_python_interpreter.startswith('/bin/')
        - not ansible_python_interpreter.startswith('/usr/bin/')

    - name: Ensure Python PyYAML and hvac modules are installed
      ansible.builtin.pip:
        name:
          - PyYAML
          - hvac
        state: latest
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"
        virtualenv: "{{ virtualenv is defined | ternary(virtualenv, omit) }}"
      become: "{{ virtualenv is not defined }}"

    - name: Ensure secret store directory exists in Kayobe configuration
      ansible.builtin.file:
        path: "{{ kayobe_env_config_path }}/{{ stackhpc_ca_secret_store }}/"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Apply vault role
      ansible.builtin.import_role:
        name: stackhpc.hashicorp.vault
      vars:
        hashicorp_registry_url: "{{ seed_hashicorp_registry_url }}"
        hashicorp_registry_username: "{{ seed_hashicorp_registry_username }}"
        hashicorp_registry_password: "{{ seed_hashicorp_registry_password }}"
        consul_docker_image: "{{ seed_consul_docker_image }}"
        consul_docker_tag: "{{ seed_consul_docker_tag }}"
        consul_bind_interface: "{{ secret_store_bind_interface }}"
        vault_bind_address: "{{ secret_store_bind_address }}"
        vault_api_addr: "{{ secret_store_api_address }}"
        vault_config_dir: /opt/kayobe/vault
        vault_cluster_name: seed
        vault_docker_image: "{{ seed_vault_docker_image }}"
        vault_docker_tag: "{{ seed_vault_docker_tag }}"
        vault_write_keys_file: true
        vault_write_keys_file_path: "{{ kayobe_env_config_path }}/vault/seed-vault-keys.json"
      when: stackhpc_ca_secret_store == "vault"

    - name: Apply OpenBao role
      ansible.builtin.import_role:
        name: stackhpc.hashicorp.openbao
      vars:
        openbao_bind_addr: "{{ secret_store_bind_address }}"
        openbao_api_addr: "{{ secret_store_api_address }}"
        openbao_registry_url: "{{ seed_openbao_registry_url }}"
        openbao_registry_username: "{{ seed_openbao_registry_username }}"
        openbao_registry_password: "{{ seed_openbao_registry_password }}"
        openbao_config_dir: /opt/kayobe/openbao
        openbao_cluster_name: seed
        openbao_docker_image: "{{ seed_openbao_docker_image }}"
        openbao_docker_tag: "{{ seed_openbao_docker_tag }}"
        openbao_write_keys_file: true
        openbao_write_keys_file_path: "{{ kayobe_env_config_path }}/openbao/seed-openbao-keys.json"
      when: stackhpc_ca_secret_store == "openbao"

    - name: Include {{ stackhpc_ca_secret_store }} keys
      ansible.builtin.include_vars:
        file: "{{ kayobe_env_config_path }}/{{ stackhpc_ca_secret_store }}/seed-{{ stackhpc_ca_secret_store }}-keys.json"
        name: secret_store_keys

    - name: Unseal {{ stackhpc_ca_secret_store }}
      ansible.builtin.import_role:
        name: stackhpc.hashicorp.vault_unseal
      vars:
        vault_api_addr: "{{ secret_store_api_address }}"
        vault_unseal_keys: "{{ secret_store_keys.keys_base64 }}"

    - name: Apply PKI role
      ansible.builtin.import_role:
        name: stackhpc.hashicorp.vault_pki
      vars:
        vault_api_addr: "{{ secret_store_api_address }}"
        vault_token: "{{ secret_store_keys.root_token }}"
        vault_pki_root_ca_name: OS-TLS-ROOT
        vault_pki_write_root_ca_to_file: true
        vault_pki_intermediate_ca_name: OS-TLS-INT
        vault_pki_intermediate_export: true
        vault_pki_intermediate_roles: "{{ seed_vault_pki_roles if stackhpc_ca_secret_store == 'vault' else seed_openbao_pki_roles }}"
        vault_pki_certificates_directory: "{{ kayobe_env_config_path }}/{{ stackhpc_ca_secret_store }}"
        vault_pki_generate_certificates: true
        vault_pki_write_certificates: true
        vault_pki_certificate_subject: "{{ seed_vault_pki_certificate_subject if stackhpc_ca_secret_store == 'vault' else seed_openbao_pki_certificate_subject }}"
        vault_pki_write_certificate_files: true
        vault_pki_write_pem_bundle: false
        vault_pki_write_int_ca_to_file: true
