---
# NTP services for overcloud hosts
# During early initialisation we use the seed Node
# Following deployment we include the OpenStack VIP

chrony_ntp_servers:
  - server: "{{ lookup('vars', admin_oc_net_name ~ '_ips')[groups.seed.0] }}"
