[pci]
{% for item in (gpu_group_map | default({})) | dict2items | map(attribute='value') | flatten | unique | list %}
alias = { "vendor_id":"{{ stackhpc_gpu_data[item].vendor_id }}", "product_id":"{{ stackhpc_gpu_data[item].product_id }}", "device_type":"{{ stackhpc_gpu_data[item].device_type }}", "name":"{{ stackhpc_gpu_data[item].resource_name }}" }
{% endfor %}
