include: .gitlab/prelude.yml

Build IPA:
  extends:
    - .tags
    - .environment-prepare
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - when: manual
  script:
    - !reference [.prelude_kayobe_setup, script]
    - .automation/pipeline/playbook-run.sh etc/kayobe/ansible/build-ipa.yml
    - mkdir ${CI_PROJECT_DIR}/artifacts
    - cp /opt/kayobe/images/ipa/ipa.{stdout,stderr} ${CI_PROJECT_DIR}/artifacts/
  artifacts:
    when: always
    paths:
      - artifacts/ipa.stdout
      - artifacts/ipa.stderr

Build Containers:
  extends:
    - .tags
    - .environment-prepare
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - when: manual
  script:
    - !reference [.prelude_kayobe_setup, script]
    - .automation/pipeline/overcloud-container-image-build.sh -e kolla_docker_registry_username=$CI_REGISTRY_USER -e kolla_docker_registry_password=$CI_REGISTRY_PASSWORD
    - mkdir ${CI_PROJECT_DIR}/artifacts
    - cp /var/log/kolla-build.log ${CI_PROJECT_DIR}/artifacts/
  artifacts:
    when: always
    paths:
      - artifacts/kolla-build.log
