# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml
# with minor modifications

include:
  - .gitlab/prelude.yml
  - template: Terraform/Base.latest.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

# Redefine .deploy from Terraform/Base.latest.gitlab-ci.yml
# to remove restriction where it will only deploy on the
# default branch.
.deploy-custom:
  stage: deploy
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform apply

before_script:
  - |
    mkdir ~/.ssh || true
    chmod 700 ~/.ssh
    echo "$KAYOBE_AUTOMATION_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.terraform
    chmod 600 ~/.ssh/id_rsa.terraform
    export TF_VAR_ssh_private_key=~/.ssh/id_rsa.terraform
    . "$TERRAFORM_OPENRC"

.job-overrides:
  rules:
    - if: $CI_MERGE_REQUEST_ID

.terraform-extras:
  variables:
    TF_STATE_NAME: $CI_ENVIRONMENT_NAME
    TF_CACHE_KEY: $CI_ENVIRONMENT_NAME
    TF_ROOT: terraform

stages:
  - init
  - validate
  - build
  - deploy
  - configure

init:
  extends:
    - .terraform-tags
    - .environment-prepare
    - .terraform-extras
    - .job-overrides
    - .init

validate:
  extends:
    - .terraform-tags
    - .environment-prepare
    - .terraform-extras
    - .job-overrides
    - .validate

build:
  extends:
    - .terraform-tags
    - .environment-prepare
    - .terraform-extras
    - .job-overrides
    - .build

deploy:
  extends:
    - .terraform-tags
    - .environment
    - .terraform-extras
    - .job-overrides
    - .deploy-custom
  allow_failure: false
  dependencies:
    - build

# Need to move this to the end!
# destroy:
#   stage: deploy
#   extends:
#   - .terraform-tags
#   - .environment
#   - .terraform-extras
#   script:
#     - cd ${TF_ROOT}
#     - gitlab-terraform destroy
#   environment:
#     action: stop
#   when: manual

configure:
  extends:
    - .tags
    - .environment
    - .job-overrides
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: configure
  script:
    - !reference [.prelude_kayobe_setup, script]
    - .automation/pipeline/overcloud-host-configure.sh
    - .automation/pipeline/overcloud-service-deploy.sh
    - .automation/pipeline/playbook-run.sh etc/kayobe/ansible/configure-aio-resources.yml
  dependencies:
    - deploy
