include: .gitlab/prelude.yml

Build IPA:
  extends:
    - .tags
    - .environment
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - if: $CI_COMMIT_REF_PROTECTED
      when: manual
  script:
    - !reference [.prelude_kayobe_setup, script]
    - .automation/pipeline/playbook-run.sh etc/kayobe/ansible/build-ipa.yml