# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml
# with minor modifications

include:
  - .gitlab/prelude.yml
  - template: Terraform/Base.latest.gitlab-ci.yml

# Redefine .deploy from Terraform/Base.latest.gitlab-ci.yml
# to remove restriction where it will only deploy on the
# default branch.
.deploy-custom:
  stage: deploy
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform apply
  when: manual

before_script:
  - |
    . "$TERRAFORM_OPENRC"

.variables:
  variables:
    TF_STATE_NAME: $CI_ENVIRONMENT_NAME
    TF_CACHE_KEY: $CI_ENVIRONMENT_NAME
    TF_ROOT: terraform

.environment-extras:
  environment:
    on_stop: destroy

stages:
  - init
  - validate
  - build
  - deploy

init:
  extends:
    - .terraform-tags
    - .environment
    - .environment-extras
    - .variables
    - .init

validate:
  extends:
    - .terraform-tags
    - .environment
    - .environment-extras
    - .variables
    - .validate

build:
  extends:
    - .terraform-tags
    - .environment
    - .environment-extras
    - .variables
    - .build

deploy:
  extends:
    - .terraform-tags
    - .environment
    - .environment-extras
    - .variables
    - .deploy-custom
  dependencies:
    - build

destroy:
  stage: deploy
  extends:
  - .terraform-tags
  - .environment
  - .environment-extras
  - .variables
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform destroy
  environment:
    action: stop
  when: manual
