# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml
# with minor modifications

include:
  - .gitlab/prelude.yml
  - template: Terraform/Base.latest.gitlab-ci.yml

# Redefine .deploy from Terraform/Base.latest.gitlab-ci.yml
# to remove restriction where it will only deploy on the
# default branch.
.deploy:
  stage: deploy
  script:
    - cd ${TF_ROOT}
    - gitlab-terraform apply
  rules:
    # NOTE: Can't use .rules here as we also want when:manual
    - if: $CI_ENVIRONMENT_NAME =~ /^aio/
      when: manual

before_script:
  - |
    . "$TERRAFORM_OPENRC"

.rules:
  rules:
    - if: $CI_ENVIRONMENT_NAME =~ /^aio/

variables:
  TF_STATE_NAME: $CI_ENVIRONMENT_SLUG
  TF_CACHE_KEY: $CI_ENVIRONMENT_SLUG
  TF_ROOT: terraform

stages:
  - init
  - validate
  - build
  - deploy

init:
  extends:
    - .terraform-tags
    - .environment
    - .rules
    - .init

validate:
  extends:
    - .terraform-tags
    - .environment
    - .rules
    - .validate

build:
  extends:
    - .terraform-tags
    - .environment
    - .rules
    - .build

deploy:
  extends:
    # NOTE: Not inheriting rules as we also want when:manual.
    - .terraform-tags
    - .environment
    - .deploy
  dependencies:
    - build

