include:
  - .gitlab/prelude.yml
  - template: Terraform/Base.latest.gitlab-ci.yml

before_script:
  - |
    . "$TERRAFORM_OPENRC"

variables:
  #TODO: set these from environment
  TF_STATE_NAME: default
  TF_CACHE_KEY: default
  TF_ROOT: terraform

stages:
  - init
  - validate
  - build
  - deploy

init:
  extends:
    - .terraform-tags 
    - .init

validate:
  extends: 
    - .terraform-tags
    - .validate

build:
  extends:
    - terraform-tags
    - .build

deploy:
  extends: 
    - terraform-tags
    - .deploy
  dependencies:
    - build

