---
# List of additional firewall rules for the seed hypervisor.
stackhpc_firewalld_rules_extra:
  # Allow SSH on the External/Admin network, since this is the administrative
  # entry point to the cloud.
  - service: ssh
    network: "external_admin"
    state: enabled
