---
- when: pulp_auth_proxy_network_mode is none
  block:
    - name: Check if Docker bridge network exists
      community.docker.docker_host_info:
        networks: true
      register: docker_host_info

    - name: Set a fact about the network mode
      ansible.builtin.set_fact:
        pulp_auth_proxy_network_mode: "{{ 'host' if docker_host_info.networks | selectattr('Driver', 'equalto', 'bridge') | list | length == 0 else 'bridge' }}"

- name: Assert that localhost is resolvable when using host networking
  assert:
    that:
      - "'localhost' is ansible.utils.resolvable"
    fail_msg: >-
      localhost must be resolvable when using Docker host networking with this container.
      Consider adding '127.0.0.1 localhost' to /etc/hosts.
  when: pulp_auth_proxy_network_mode == 'host'

- name: "Ensure {{ pulp_auth_proxy_conf_path }} exists"
  ansible.builtin.file:
    path: "{{ pulp_auth_proxy_conf_path }}"
    state: directory
    mode: 0700
  become: true

- name: Ensure pulp_proxy.conf is templated
  ansible.builtin.template:
    src: pulp_proxy.conf.j2
    dest: "{{ pulp_auth_proxy_conf_path }}/pulp_proxy.conf"
    mode: 0600
  become: true
  register: pulp_proxy_conf

- name: Ensure pulp_proxy container is running
  community.docker.docker_container:
    name: pulp_proxy
    image: nginx:stable-alpine
    network_mode: "{{ pulp_auth_proxy_network_mode }}"
    ports:
      - "{{ pulp_auth_proxy_listen_ip }}:{{ pulp_auth_proxy_listen_port }}:80"
    restart_policy: "no"
    restart: "{{ pulp_proxy_conf is changed }}"
    volumes:
      - "{{ pulp_auth_proxy_conf_path }}/pulp_proxy.conf:/etc/nginx/conf.d/default.conf:ro"

- name: Wait for pulp_proxy container to become accessible
  ansible.builtin.uri:
    url: http://localhost/pulp/api/v3/status/
  register: uri_result
  until: uri_result is success
  retries: 30
  delay: 2
