# Comments show default policy for nova.
#"os_compute_api:servers:create:forced_host": "rule:context_is_admin"
"os_compute_api:servers:create:forced_host": "rule:context_is_admin or role:baremetaluser"
#"compute:servers:create:requested_destination": "rule:context_is_admin"
"compute:servers:create:requested_destination": "rule:context_is_admin or role:baremetaluser"
