---
nvue_switch_config_interfaces_shared:
  swp1:
    config:
      - link breakout 2x
  swp1s0:
    description: "Hypervisor 1"
  bond1s0:
    description: "Hypervisor 1"
    config:
      - bond member swp1s0
  swp1s1:
    description: "Control Plane 1"
  bond1s1:
    description: "Control Plane 1"
    config:
      - bond member swp1s1
  swp2:
    config:
      - link breakout 2x
  swp2s0:
    description: "GPU Node 7"
  bond2s0:
    description: "GPU Node 7"
    config:
      - bond member swp2s0
  swp2s1:
    description: "Control Plane 3"
  bond2s1:
    description: "Control Plane 3"
    config:
      - bond member swp2s1
  swp3:
    config:
      - link breakout 2x
  swp3s0:
    description: "GPU Node 6"
  bond3s0:
    description: "GPU Node 6"
    config:
      - bond member swp3s0
  swp3s1:
    description: "GPU Node 5"
  bond3s1:
    description: "GPU Node 5"
    config:
      - bond member swp3s1
  swp4:
    config:
      - link breakout 2x
  swp4s0:
    description: "GPU Node 4"
  bond4s0:
    description: "GPU Node 4"
    config:
      - bond member swp4s0
  swp4s1:
    description: "Control Plane 2"
  bond4s1:
    description: "Control Plane 2"
    config:
      - bond member swp4s1
  swp5:
    config:
      - link breakout 2x
  swp5s0:
    description: "GPU Node 3"
  bond5s0:
    description: "GPU Node 3"
    config:
      - bond member swp5s0
  swp5s1:
    description: "GPU Node 2"
  bond5s1:
    description: "GPU Node 2"
    config:
      - bond member swp5s1
  swp6:
    config:
      - link breakout 2x
  swp6s0:
    description: "GPU Node 1"
  bond6s0:
    description: "GPU Node 1"
    config: "{{ switch_interface_config_gpu }}"


