nodes:
  # Indexer server nodes
  indexer:
    - name: artemis-wazuh-01
      ip: 10.171.0.1

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:

  # Dashboard node
  dashboard:
