---
- hosts: all
  vars:
    script_path: "/home/zuul/src/github.com/stackhpc/stackhpc-kayobe-config/etc/kayobe/environments/ci-gns3/gns3-deployment.sh"
  tasks:
    - name: Run deploy script
      environment:
        KAYOBE_CONFIG_REF: "{{ zuul.patchset }}"
      shell:
        cmd: "{{ script_path }}"
        executable: /bin/bash
    
