---
- name: Push OFED packages
  hosts: ofed-builder
  vars:
    venv: "/opt/kayobe/venvs/kayobe"
    doca_extract_path: "/home/stack/doca"
  tasks:
    - name: Get OFED module repo
      ansible.builtin.set_fact:
        doca_modules_repos: "{{ stackhpc_pulp_rpm_repos | selectattr('name', 'search', 'OFED') | selectattr('base_path', 'search', '/rhel' ~ os_release) | selectattr('base_path', 'search', '/' ~ os_arch ~ '/') | list }}"

    - name: Assert OFED module repo is unique
      ansible.builtin.assert:
        that:
          - doca_modules_repos | length == 1
        fail_msg: "Expected exactly one OFED module repo for {{ os_arch }}"

    - name: Get OFED module repo variables
      ansible.builtin.set_fact:
        doca_modules_repo_name: "{{ doca_modules_repos.0.name }}"
        doca_modules_repo_base_path: "{{ doca_modules_repos.0.base_path }}"
        doca_modules_repo_distribution_name: "{{ doca_modules_repos.0.distribution_name }}"

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - pyopenssl
          - ndg-httpsclient
          - pyasn1
          - urllib3
          - packaging
          - pulp-glue<0.34.0,>=0.33.0
          - pulp-glue-deb<0.4.0,>=0.3.0
        state: present

    - name: Find DOCA kernel repo package
      ansible.builtin.shell:
        cmd: 'find /tmp/DOCA.* -name doca-kernel-repo-*'
      register: doca_kernel_repo
      changed_when: false

    - name: Create Pulp repository for DOCA kernel modules
      pulp.squeezer.rpm_repository:
        pulp_url: "{{ stackhpc_release_pulp_url }}"
        username: "{{ stackhpc_release_pulp_username }}"
        password: "{{ stackhpc_release_pulp_password }}"
        name: "{{ doca_modules_repo_name }}"
        state: present
      register: repository
      until: repository is success
      retries: "{{ pulp_timeout_retries | default(3) | int }}"
      delay: "{{ pulp_delay | default(5) | int }}"

    - name: Upload OFED RPMs to Pulp
      pulp.squeezer.rpm_package:
        pulp_url: "{{ stackhpc_release_pulp_url }}"
        username: "{{ stackhpc_release_pulp_username }}"
        password: "{{ stackhpc_release_pulp_password }}"
        file: "{{ item }}"
        chunk_size: 4194304
        repository: "{{ doca_modules_repo_name }}"
        state: present
      with_items: "{{ doca_kernel_repo.stdout_lines }}"
      register: package
      until: package is success
      retries: "{{ pulp_timeout_retries | default(3) | int }}"
      delay: "{{ pulp_delay | default(5) | int }}"

    - name: Create Pulp publication for OFED
      pulp.squeezer.rpm_publication:
        pulp_url: "{{ stackhpc_release_pulp_url }}"
        username: "{{ stackhpc_release_pulp_username }}"
        password: "{{ stackhpc_release_pulp_password }}"
        repository: "{{ doca_modules_repo_name }}"
        state: present
      register: publication

    - name: Create Pulp distribution for OFED
      pulp.squeezer.rpm_distribution:
        pulp_url: "{{ stackhpc_release_pulp_url }}"
        username: "{{ stackhpc_release_pulp_username }}"
        password: "{{ stackhpc_release_pulp_password }}"
        name: "{{ doca_modules_repo_distribution_name + ofed_tag }}"
        publication: "{{ publication.publication.pulp_href }}"
        content_guard: release
        base_path: "{{ doca_modules_repo_base_path + ofed_tag }}"
        state: present
