---
features:
  - |
    Adds kolla config merging options to the ``Kolla custom config generation``
    section of ``etc/kayobe/kolla.yml``.
upgrade:
  - |
    `Kolla config merging is enabled by default in the Antelope release of Kayobe
    <https://github.com/stackhpc/kayobe/pull/174>`__.
    This was quite an extensive change and whilst backwards compatbility was
    one of the goals, there may be some situations where refactoring of your
    Kolla config will be necessary. Extra care should be taken if you are using
    the multiple environments feature. It is recommended that you carefully
    check the diff in the resultant Kolla configuration by following `these steps
    <https://stackhpc.github.io/openstack-admin-guide/working_with_kayobe.html#verifying-changes-before-applying>`__
    to check for missing config or duplicated config options. The
    ``kolla_openstack_custom_config_environment_merging_enabled`` option can
    be set to ``False`` to revert back to the old behaviour.

