---
fixes:
  - |
    Disabled custom APT configuration for non-overcloud hosts (Ubuntu Only).
    This resolves the issue of the seed hypervisor attempting to pull packages
    from the repository on the seed before it has been deployed.
