---
global:
  resolve_timeout: 5m
  smtp_require_tls: true
  slack_api_url: {{ secrets_slack_notification_channel_url }}

route:
  receiver: 'slack-notifications'
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - matchers:
        - severity=~"critical|alert"
      receiver: 'slack-critical-notifications'

 
receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#artemis-alerts'
      actions:
      - type: button
        text: 'Silence 🔕'
        url: {{ '{% raw %}' }}{% raw %} '{{ template "__alert_silence_link" . }}' 
{% endraw %}{{ '{% endraw %}' }}
      send_resolved: true
  - name: 'slack-critical-notifications'
    slack_configs:
    - channel: '#artemis-critical-alerts'
      actions:
      - type: button
        text: 'Silence 🔕'
        url: {{ '{% raw %}' }}{% raw %} '{{ template "__alert_silence_link" . }}' 
{% endraw %}{{ '{% endraw %}' }}
      send_resolved: true
      api_url: {{ secrets_slack_critical_notification_channel_url }}


templates:
  - '/etc/prometheus/*.tmpl'
