---
ironic_driver: redfish

ironic_driver_info:
  redfish_address: "{{ ironic_redfish_address }}"
  redfish_username: "{{ ironic_redfish_username }}"
  redfish_password: "{{ ironic_redfish_password }}"
  redfish_verify_ca: "{{ ironic_redfish_verify_ca }}"

ironic_redfish_verify_ca: false
ironic_redfish_address: "{{ redfish_address }}"
ironic_redfish_username: "{{ secrets_redfish_baremetal_username }}"
ironic_redfish_password: "{{ secrets_redfish_baremetal_password }}"
