############################################################################
# This content is copied into globals.yml during automated setup, but cannot
# exist during the initial configuration

# Internal TLS configuration
# Copy the self-signed CA into the kolla containers
kolla_copy_ca_into_containers: "yes"
# Use the following trust store within the container
openstack_cacert: "{{ '/etc/pki/tls/certs/ca-bundle.crt' if os_distribution == 'rocky' else '/etc/ssl/certs/ca-certificates.crt' }}"

# Backend TLS config
# Enable backend TLS
kolla_enable_tls_backend: "yes"

# If using RabbitMQ TLS:
rabbitmq_enable_tls: "yes"

############################################################################
