---
# https://docs.openstack.org/ironic/2023.1/admin/drivers/idrac.html
inspector_default_node_driver: "idrac"
enabled_hardware_types: "idrac"
enabled_bios_interfaces: "idrac-redfish"
enabled_boot_interfaces: "ipxe,idrac-redfish-virtual-media"
enabled_deploy_interfaces: "direct"
enabled_management_interfaces: "idrac-redfish"
enabled_power_interfaces: "idrac-redfish"
enabled_raid_interfaces: "idrac-redfish"

###############################################################################
# Dummy variable to allow Ansible to accept this file.
workaround_ansible_issue_8743: yes
