---
inspector_default_node_driver: "redfish"
enabled_hardware_types: "redfish"
enabled_bios_interfaces: "redfish"
enabled_boot_interfaces: "ipxe"
enabled_deploy_interfaces: "direct"
enabled_management_interfaces: "redfish"
enabled_power_interfaces: "redfish"
enabled_raid_interfaces: "redfish"

###############################################################################
# Dummy variable to allow Ansible to accept this file.
workaround_ansible_issue_8743: yes