---
- name: Remove legacy os_exporter.cfg file
  hosts: network
  gather_facts: false
  tasks:
    - name: Ensure legacy os_exporter.cfg config file is deleted
      ansible.builtin.file:
        path: /etc/kolla/haproxy/services.d/os_exporter.cfg
        state: absent
      become: true

- name: Deploy os-capacity exporter
  hosts: monitoring
  gather_facts: false
  tasks:
    - name: Create os-capacity directory
      ansible.builtin.file:
        path: /opt/kayobe/os-capacity/
        state: directory

    - name: Template clouds.yml
      ansible.builtin.template:
        src: templates/os_capacity-clouds.yml.j2
        dest: /opt/kayobe/os-capacity/clouds.yaml

    - name: Ensure os_capacity container is running
      docker_container:
        name: os_capacity
        image: ghcr.io/stackhpc/os-capacity:master
        env:
          OS_CLOUD: openstack
          OS_CLIENT_CONFIG_FILE: /etc/openstack/clouds.yaml
        mounts:
          - type: bind
            source: /opt/kayobe/os-capacity/
            target: /etc/openstack/
        network_mode: host
        restart_policy: unless-stopped
      become: true
