---
- name: Deploy Hashicorp Vault on the seed
  any_errors_fatal: True
  gather_facts: True
  hosts: seed
  vars:
    vault_api_addr: "http://127.0.0.1:8200"
  tasks:
    - name: Set a fact about the virtualenv on the remote system
      set_fact:
        virtualenv: "{{ ansible_python_interpreter | dirname | dirname }}"
      when:
        - ansible_python_interpreter is defined
        - not ansible_python_interpreter.startswith('/bin/')
        - not ansible_python_interpreter.startswith('/usr/bin/')

    - name: Ensure Python hvac module is installed
      pip:
        name: hvac
        state: latest
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"
        virtualenv: "{{ virtualenv is defined | ternary(virtualenv, omit) }}"
      become: "{{ virtualenv is not defined }}"

    - name: Include Vault keys
      include_vars:
        file: "{{ kayobe_env_config_path }}/vault/seed-vault-keys.json"
        name: vault_keys

    - import_role:
        name: stackhpc.hashicorp.vault_unseal
      vars:
        vault_unseal_keys: "{{ vault_keys.keys_base64 }}"
