---
- name: Deploy GitHub Runner
  hosts: github-runners
  become: true
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
  tasks:
    - name: Set custom_env fact if any proxy variable is defined
      set_fact:
        custom_env: |
          http_proxy={{ http_proxy | default('') }}
          https_proxy={{ https_proxy | default('') }}
          no_proxy={{ (['localhost', '127.0.0.1', '127.0.0.2'] + (no_proxy | default([]))) | join(',') }}
      when: >
        http_proxy is defined or
        https_proxy is defined or
        no_proxy is defined

    - name: Deploy runners
      ansible.builtin.include_role:
        name: monolithprojects.github_actions_runner
      vars:
        runner_name: "{{ ansible_facts.nodename }}-{{ runner.key }}"
        runner_dir: "{{ base_runner_dir }}/{{ runner.key }}"
        runner_labels: "{{ runner.value.labels | default(default_runner_labels) }}"
        runner_state: "{{ runner.value.state | default('started') }}"
      with_dict: "{{ github_runners }}"
      loop_control:
        loop_var: runner

    # FIXME: Sometimes the runner service is not running at the end of the role.
    # Start the service manually.
    - name: Ensure runner service is running
      ansible.builtin.service:
        name: actions.runner.{{ github_account }}-{{ github_repo }}.{{ ansible_facts.nodename }}-{{ runner.key }}.service
        state: started
        enabled: true
      become: true
      when: runner_state | default('started') == 'started'
      with_dict: "{{ github_runners }}"
      loop_control:
        loop_var: runner
