---
- name: Write Kayobe Automation Pipeline for GitLab
  hosts: gitlab-writer
  vars:
    gitlab_output_directory: "{{ lookup('env', 'KAYOBE_CONFIG_PATH') }}/../../"
  roles:
    - stackhpc.kayobe_workflows.gitlab
