---
- name: Write Kayobe Automation Workflows for GitHub
  hosts: github-writer
  vars:
    github_output_directory: "{{ lookup('env', 'KAYOBE_CONFIG_PATH') }}/../../.github/workflows"
  roles:
    - stackhpc.kayobe_workflows.github
