---
- project:
    queue: kayobe
    check:
      jobs:
        - openstack-tox-pep8

    check-review:
      jobs:
        - tenks-ubuntu-noble
        - tenks-rocky-9
        - tenks-rocky-10

    gate:
      jobs:
        - openstack-tox-pep8
        - tenks-ubuntu-noble
        - tenks-rocky-9
        - tenks-rocky-10
