---
- project:
    queue: kayobe
    check:
      jobs:
        - openstack-tox-pep8

    check-review:
      jobs:
        #TODO(mattcrees): Re-enable once Bifrost is patched to stop leaking creds:
        # https://review.opendev.org/c/openstack/bifrost/+/1008093
        #- tenks-ubuntu-noble
        #- tenks-rocky-9
        #- tenks-rocky-10
        - gns3-test-physical-network-ubuntu
        - gns3-test-ngs-ubuntu

    gate:
      jobs:
        - openstack-tox-pep8
        #TODO(mattcrees): Re-enable once Bifrost is patched to stop leaking creds:
        # https://review.opendev.org/c/openstack/bifrost/+/1008093
        #- tenks-ubuntu-noble
        #- tenks-rocky-9
        #- tenks-rocky-10
