---
###############################################################################
# Network interface definitions for the seed group.

external_admin_interface: "eth0"

mgmt_oc_interface: "eth1"

provision_oc_interface: "{{ mgmt_oc_interface }}.{{ provision_oc_untagged_vlan }}"
