---
switch_interface_config:
  eth0:
    description: "Management"
    config:
      - ip address {{ ansible_host }}/{{ oob_oc_net_name | net_prefix }}
  swp1:
    description: artemis-hv-01
    config: "{{ switch_interface_config_overcloud | from_yaml }}"
  swp2:
    description: artemis-cp-01
    config: "{{ switch_interface_config_overcloud | from_yaml }}"
  swp3:
    description: artemis-gpu-07
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp4:
    description: artemis-cp-03
    config: "{{ switch_interface_config_overcloud | from_yaml }}"
  swp5:
    description: artemis-gpu-06
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp6:
    description: artemis-gpu-05
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp7:
    description: artemis-gpu-04
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp8:
    description: artemis-cp-02
    config: "{{ switch_interface_config_overcloud | from_yaml }}"
  swp9:
    description: artemis-gpu-03
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp10:
    description: artemis-gpu-02
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp11:
    description: artemis-gpu-01
    config: "{{ switch_interface_config_baremetal | from_yaml }}"
  swp12:
    description: ceres
    config: "{{ switch_interface_config_seed_hypervisor | from_yaml }}"

switch_interface_config_overcloud: |
  {{ switch_interface_config_up }}
  {{ switch_interface_config_bridge_domain }}
  {{ switch_interface_config_stp_edge }}
  - bridge domain br_default access {{ provision_oc_untagged_vlan }}

switch_interface_config_baremetal: |
  {{ switch_interface_config_bridge_domain }}
  {{ switch_interface_config_stp_edge }}
  {% if physical_network_enable_discovery | default(false) | bool %}
  {{ switch_interface_config_up }}
  - bridge domain br_default access {{ provision_wl_untagged_vlan }}
  {% endif %}
  {% if physical_network_disable_discovery | default(false) | bool %}
  {{ switch_interface_config_down }}
  - bridge domain br_default access 1
  {% endif %}

switch_interface_config_seed_hypervisor: |
  {{ switch_interface_config_up }}
  {{ switch_interface_config_bridge_domain }}
  {{ switch_interface_config_stp_edge }}
  - bridge domain br_default access {{ provision_oc_untagged_vlan }}
