---
# This workflow builds required versions of OVN and OVS for
# Rocky Linux 10 then pushes them to a registry.

# This will only be needed until we move to newer OVN/OVS
# packages, which already exist in the NFV SIG repository for
# CentOS Stream 10.

name: Build Rocky 10 OVN/OVS Packages
on: workflow_dispatch

jobs:
  run-away:
    runs-on: ubuntu-latest
    steps:
      - name: Print message and run away
        run: echo "This workflow is not operational yet"
