name: Build kayobe image

# Build a new image when ever a release is tagged.
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    container: docker:20.10.21-git
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout kayobe config
        uses: actions/checkout@v2
        with:
           submodules: true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          # Don't tag alpha images with latest. This allows you to tag a
          # pre-release image for testing.
          flavor: |
           latest=${{ !contains(github.ref, 'alpha') }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2
        with:
          ssh-private-key: ${{ secrets.KAYOBE_AUTOMATION_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
         driver-opts: |
           image=moby/buildkit:master

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./.automation/docker/kayobe/Dockerfile
          context: .
          build-args: |
             KAYOBE_DOCKER_SSH_CONFIG_PATH=.automation/docker/kayobe/ssh_config
             KAYOBE_ENVIRONMENT=habrok
             KAYOBE_USER_UID=1001
             KAYOBE_USER_GID=1001
          ssh: default
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

