name: hello-world-example
on:
  push:
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"
      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      -
        name: Say Goodbye
        run: echo "Goodbye!"