name: Run overcloud service deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: |
          Force the job to use a particular environment. Use this when not using a
          recognised branch e.g to test a change before merging.
        type: choice
        options:
          - habrok
          - merlin
      kayobeLimit:
        description: |
          The ansible limit to use when running kayobe playbooks.
      kayobeTags:
        description: |
          The ansible tags to use when running kayobe playbooks.
      kollaLimit:
        description: |
          The ansible limit to use for kolla-ansible playbooks.
      kollaTags:
        description: |
          The ansible tags to use when running kolla-ansible playbooks.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  env:
    uses: ./.github/workflows/environment-variables.yml
    with:
      baseRef: ${{ github.base_ref }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  overcloud-service-deploy:
    runs-on: ${{ fromJSON(needs.env.outputs.runs_on) }}
    environment: ${{ needs.env.outputs.environment }}
    concurrency: ${{ needs.env.outputs.environment }}-overcloud
    needs: env
    permissions:
      pull-requests: write
      contents: write
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}:${{needs.env.outputs.kayobeImageTag}}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Print the environment specific variables
        run: echo "$ENV_VARS"
        env:
          ENV_VARS: ${{ toJSON(needs.env.outputs) }}

      - name: Print workflow inputs
        run: echo "$INPUTS"
        env:
          INPUTS: ${{ toJSON(github.event.inputs) }}

      - name: Checkout kayobe config
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Symlink source checkout to expected location
        run: sudo ln -s $PWD /src

      - name: Run overcloud service deploy
        run: |
          /src/.automation/pipeline/overcloud-service-deploy.sh
        env:
          KOLLA_LIMIT: "${{ github.event.inputs.kollaLimit }}"
          KOLLA_TAGS: "${{ github.event.inputs.kollaTags }}"
          KAYOBE_TAGS: "${{ github.event.inputs.kayobeTags }}"
          KAYOBE_LIMIT: "${{ github.event.inputs.kayobeLimit }}"
          KAYOBE_AUTOMATION_PR_TARGET_BRANCH: ${{ github.event.ref }}
          KAYOBE_AUTOMATION_PR_REMOTE: https://${KAYOBE_AUTOMATION_PR_GITHUB_USER}:${KAYOBE_AUTOMATION_PR_AUTH_TOKEN}@github.com/${{ github.repository }}
          KAYOBE_AUTOMATION_PR_GITHUB_USER: ${{ github.actor }}
          KAYOBE_AUTOMATION_PR_AUTH_TOKEN: ${{ github.token }}
          KAYOBE_AUTOMATION_PR_TYPE: github
          KAYOBE_AUTOMATION_PR_TITLE: "[kayobe-automation] ${{ github.workflow }} #${{ github.run_id }}"
          KAYOBE_AUTOMATION_PR_URL: https://api.github.com/repos/${{ github.repository }}/pulls
          HOME: /stack

