name: Update Kolla versions

on:
  # Allow manual executions
  workflow_dispatch:
  # Run weekly on Tuesday
  schedule:
    - cron: '0 0 * * 2'

jobs:
  update-from-branch:
    name: Update dependencies
    strategy:
      matrix:
        include:
          - version: stackhpc/2023.1
          - version: stackhpc/2024.1
          - version: stackhpc/2025.1
    uses: ./.github/workflows/update-dependencies.yml
    with:
      branch: ${{ matrix.version }}
    permissions:
      contents: write
      pull-requests: write
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
