---

concurrency:
  group: stackhpc-pull-request-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Pull request
'on':
  push:
jobs:
  # Detect which files have changed and use this to run jobs conditionally.
  # Note that we can't use the workflow-level paths attribute since this
  # would skip the workflow entirely, and would prevent us from making the
  # aio jobs required to pass (a skip counts as a pass).
  build-kayobe-image:
    name: Build Kayobe Image
    uses: ./.github/workflows/stackhpc-build-kayobe-image.yml
    with:
      if: ${{ needs.check-changes.outputs.build-kayobe-image == 'true' }}
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'

  check-tags:
    name: Check container image tags
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-check-tags.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      if: ${{ needs.check-changes.outputs.check-tags == 'true' }}
    secrets: inherit
    if: ${{ ! failure() && ! cancelled() && github.repository == 'stackhpc/stackhpc-kayobe-config' }}

  all-in-one-upgrade-rocky-9-ovn:
    name: aio upgrade (Rocky 9 OVN)
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-all-in-one.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: rocky
      os_release: "9"
      ssh_username: cloud-user
      neutron_plugin: ovn
      OS_CLOUD: openstack
      upgrade: true
    secrets: inherit
    if: ${{ ! failure() && ! cancelled() && github.repository == 'stackhpc/stackhpc-kayobe-config' }}

  all-in-one-upgrade-rocky-9-ovs:
    name: aio upgrade (Rocky 9 OVS)
    needs:
      - build-kayobe-image
    uses: ./.github/workflows/stackhpc-all-in-one.yml
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: rocky
      os_release: "9"
      ssh_username: cloud-user
      neutron_plugin: ovs
      OS_CLOUD: openstack
      upgrade: true
    secrets: inherit
    if: ${{ ! failure() && ! cancelled() && github.repository == 'stackhpc/stackhpc-kayobe-config' }}
