---
name: Upstream Sync
'on':
  schedule:
    - cron: "15 8 * * 1"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  synchronise-2023-1:
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
    name: Synchronise 2023.1
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: 2023.1
      upstream: openstack/kayobe-config
  synchronise-2024-1:
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
    name: Synchronise 2024.1
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: 2024.1
      upstream: openstack/kayobe-config
  synchronise-2025-1:
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
    name: Synchronise 2025.1
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: 2025.1
      upstream: openstack/kayobe-config
  synchronise-master:
    if: github.repository == 'stackhpc/stackhpc-kayobe-config'
    name: Synchronise master
    uses: stackhpc/.github/.github/workflows/upstream-sync.yml@main
    with:
      release_series: master
      upstream: openstack/kayobe-config
